### ISSUE TITLE
Clear page button cannot be shown in White Board

### ISSUE THREAD

**Issue by Sdarfeesh** [adil192/saber#100]
https://user-images.githubusercontent.com/50188628/204663588-e0af9b6e-f2e2-4ba7-8200-d2b2955cdc05.mp4

**Comment by adil192** [comment]
Are you using a beta release from [Actions](https://github.com/adil192/saber/actions/workflows/android.yml)?

**Comment by adil192** [comment]
Ah okay, please include that if you submit any other issues /nm
