### ISSUE TITLE
Which version should I Download ?

### ISSUE THREAD

**Issue by hfyryhr656tre** [adil192/saber#104]
Can I use this on Windows 7 32 bit PC.
If Yes then which version should I download
please give the link

**Comment by adil192** [comment]
Hi, 32-bit Windows isn't supported by Flutter https://github.com/flutter/flutter/issues/37777.
You can instead use the web app at https://saber.adil.hanney.org (though syncing isn't working yet).

**Comment by hfyryhr656tre** [comment]
No I was asking for the Saber notes app 
Is it supported on Windows 7 32 bit PC

**Comment by adil192** [comment]
Saber is built with Flutter so no it's not supported
