### ISSUE TITLE
Rotating screen sometimes clears whiteboard

### ISSUE THREAD

**Issue by EinHerrK** [adil192/saber#106]
I noticed when I repeatedly switch between portrait and landscape orientation the app reproducibly clears the content of a note after a few switches. 

I'm using the latest  0.4.1 build from F-Droid.

**Comment by adil192** [comment]
I can't seem to reproduce this on my phone

**Comment by EinHerrK** [comment]
I recorded a video of the effect... I just drew something on the whiteboard, then turned the phone a couple of times. Drawing vanishes.

I'm on a Samsung Galaxy S10e with LineageOS 19.1, if that's relevant... if you need any more information, let me know!


https://user-images.githubusercontent.com/16221316/205443352-dcc4da53-6465-4120-94e3-af60136925ad.mp4

**Comment by adil192** [comment]
Found out that this is exclusive to the whiteboard. Seems fixed to me in [Build #44](https://github.com/adil192/saber/actions/runs/3612909026)

**Comment by EinHerrK** [comment]
Thanks for the quick fix! And apologies for the unclear bug description, my mistake -.-

Can't install the apk of the build on my phone for some reason, but I'll test again when it becomes available on F-Droid.

**Comment by adil192** [comment]
The F-Droid build will have an incompatible signature with my build, so you can either uninstall then install the new one or wait for the next release on F-Droid. And no worries, debugging is my job!
