### ISSUE TITLE
For custom nextcloud, allow upload to non-encrypted backends

### ISSUE THREAD

**Issue by Redmattski** [adil192/saber#116]
Self hosted nextcloud repositories may not require backend encryption.   Saber only allow connection to a nextcloud server that has backend encryption enabled.

**Comment by adil192** [comment]
Saber handles all its encryption itself. Is this a problem you're experiencing?

**Comment by Redmattski** [comment]
I have Saber installed on an android device and when I try to connect to my nextcloud instance it insists that it needs an encryption password.   Since my nextcloud instance runs from a local machine, I do not have encryption switched on, so I am not able to connect to my nextcloud instance.

**Comment by Redmattski** [comment]
OK - I clearly misunderstood the design.

To clarify, I am having issues connecting to my nextcloud instance with saber.   Adding my server, username and password plus an encryption key and the android app doesn't seem to connect, even on the same LAN.

I don't have server-side encryption enabled or installed so I assumed that was the issue but if the encryption is client side.  I am trying to understand if this issue is a setting on the server side or on the client side.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adil192** [comment]
I'm assuming that you can connect to your Nextcloud server website using your android device. Are you able to form a WebDAV connection to it: [Accessing Nextcloud files using WebDAV](https://docs.nextcloud.com/server/20/user_manual/en/files/access_webdav.html)?

**Comment by Redmattski** [comment]
I can connect to webdav from linux and android with

davs://nextcloud.example.org/remote.php/webdav

This isn't working for Saber.

Thanks


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adil192** [comment]
The Nextcloud website I linked above has a slightly different url, I'm not sure if this would make a difference.
```
davs://example.com/nextcloud/remote.php/dav/files/USERNAME/
```

[This page](https://help.nextcloud.com/t/webdav-remote-access-kodi-error/58160/3) says there might be an issue if you use a self-signed certificate?

**Comment by Redmattski** [comment]
Hi

I have a certificate from Let's Encrypt, so self signing issues should not apply.

By updating the .htaccess redirect rules, I can connect to my server via davs://example.com/nextcloud/remote.php/dav/

Still having issues connecting via Saber app.

Note: my nextcloud server is built on Arch Linux




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adil192** [comment]
I'm really not sure then. I didn't do anything special with regards to [nc.saber.adil.hanney.org](https://nc.saber.adil.hanney.org)
