### ISSUE TITLE
Making note with same name or substring overwrites others

### ISSUE THREAD

**Issue by quazar-omega** [adil192/saber#117]
This is displaying weird behaviour as you can see here:

https://user-images.githubusercontent.com/56311398/206511967-575dd80f-2061-41ba-83e5-d035a201ddd8.mp4

Do you base your database keys on the title of the note? If so, I think it would be better to move to a simple number id mechanism

**Comment by adil192** [comment]
> Do you base your database keys on the title of the note? If so, I think it would be better to move to a simple number id mechanism

The notes are stored as actual files. This is definitely not intended behaviour though; I'll add a check to avoid overwriting existing notes. Good spot!

**Comment by quazar-omega** [comment]
> The notes are stored as actual files.

Oh I see, sorry if I'm responding so late, but I started thinking about this from a UX perspective after I skimmed through the source to understand a little better and I wanted to open a discussion, but I couldn't get properly to it until now.

Anyway, great work! I cannot emphasize enough how amazing your app is!

**Comment by adil192** [comment]
You just reminded me of a bug I spotted while working on another feature!

**Comment by quazar-omega** [comment]
Haha, would you look at that, the coincidences!
