### ISSUE TITLE
Adding Grid and Ruled Lines for Android

### ISSUE THREAD

**Issue by VihagChaturvedi** [adil192/saber#119]
Great app, love it! I am personally migrating from OneNote and want to use Saber as a replacement for it.

I generally use hand written notes for school notes and need to draw diagrams, which is why grid lines are essential for my use. The app otherwise seems perfect. Thank you for your work :)

**Comment by adil192** [comment]
You can find the background options by tapping the menu buttons at the top of the editor :)
