### ISSUE TITLE
Crashed when pressing the button on s-pen

### ISSUE THREAD

**Issue by jungleclaptrap** [adil192/saber#124]
Device: Samsung S tab 7 fe

It crashes even when not in drawing mode.

Seems like the app was not designed to handle the s-pen button.

**Comment by adil192** [comment]
Sadly I can't do much about this. It was first reported in https://github.com/adil192/saber/issues/21 and the upstream issue is https://github.com/flutter/flutter/issues/111068. It has been fixed by Flutter but it's not in the stable release yet.
