### ISSUE TITLE
S-pen button force close

### ISSUE THREAD

**Issue by Naheel-Azawy** [adil192/saber#125]
Hello,

I was looking for a free alternative for Samsung Notes app. There're still many features to be implemented, but this is the best I found so far. Overall, great work!

To the point, on my Galaxy Note 10, pressing the S-pen button and drawing is expected to function as an eraser. However, doing so in Saber force closes the application. It would be great if this can be fixed and even better if it can function as an eraser.

**Comment by jungleclaptrap** [comment]
https://github.com/adil192/saber/issues/124

**Comment by adil192** [comment]
Sadly I can't do much about this. It was first reported in https://github.com/adil192/saber/issues/21 and the upstream issue is https://github.com/flutter/flutter/issues/111068. We're waiting for it to be released in Flutter stable.

**Comment by Naheel-Azawy** [comment]
Ok, let's hope they will do something about it.
Fascinating work regardless
