### ISSUE TITLE
Cannot use a nextcloud server served under a /path

### ISSUE THREAD

**Issue by yajo** [adil192/saber#13]
Trying to log in a custom nextcloud hosted in `https://example.com/nextcloud` fails:

![imagen](https://user-images.githubusercontent.com/973709/190476664-c3f396bf-e3ea-4421-8758-00663e02eef1.png)

**Comment by adil192** [comment]
Oh no! Thanks for the report @yajo I'll fix this asap

**Comment by adil192** [comment]
This will be fixed with the next update
