### ISSUE TITLE
Traditional Chinese not display in Build

### ISSUE THREAD

**Issue by jhihyulin** [adil192/saber#136]
**Describe the bug**
Traditional Chinese cannot be displayed normally.

**To Reproduce**
[Build for Android #60](https://github.com/adil192/saber/actions/runs/3667892324) ❌
[Build for Android #59](https://github.com/adil192/saber/actions/runs/3667415307) ❌
[Build for Android #57](https://github.com/adil192/saber/actions/runs/3666289205) ✅

**Expected behavior**
Display the interface in Traditional Chinese. 

**Screenshots**

60|59|57
---|---|---
![60](https://user-images.githubusercontent.com/74854953/206896745-54c92f4f-4d1b-4a8b-afac-b79a7b05ee12.jpg)|![59](https://user-images.githubusercontent.com/74854953/206896767-4b6c1d6a-4e8e-4dce-871e-afb9b09cd939.jpg)|![57](https://user-images.githubusercontent.com/74854953/206896778-f427e9e4-c5da-4a7f-8146-365eb7867ee4.jpg)

**Device**
 - Device: [RMX2075TW & Pixel6 Emulator]
 - OS: [Android 12]
 - Version: [N/A]

**Comment by adil192** [comment]
Thanks for catching this. Please can you try [Build for Android #61](https://github.com/adil192/saber/actions/runs/3670044499)?

**Comment by jhihyulin** [comment]
It still doesn't work

**Comment by adil192** [comment]
What about [Build #63](https://github.com/adil192/saber/actions/runs/3671137200)?

**Comment by jhihyulin** [comment]
You fixed it, thanks
