### ISSUE TITLE
The logging in animation keeps spinning in the saber app and and doesn't sign in to my nc server as well.

### ISSUE THREAD

**Issue by watson96** [adil192/saber#143]
> the logging in animation keeps spinning in the saber app.

If you mean the button on the login page, this should be fixed in v0.4.6 when it releases

_Originally posted by @adil192 in https://github.com/adil192/saber/issues/118#issuecomment-1345694122_

Not just the button but doesn't sign in itself. It is creating the folder in my nc instance but doesn't sign in and sync isn't working. From my side my nc instance is working fine.

**Comment by adil192** [comment]
Please can you try deleting the Saber folder in your Nextcloud server?

**Comment by adil192** [comment]
Any updates?

**Comment by watson96** [comment]
Yeah tried that. I just noticed that I have some webfinger errors in my instance so I will try to fix those and get back.

**Comment by adil192** [comment]
I'm going to close nextcloud issues from now on as there's not much I can do to help, and the other nextcloud issue resolved itself with no changes from me.
