### ISSUE TITLE
How to delete a note?

### ISSUE THREAD

**Issue by adil192** [adil192/saber#15]
### Discussed in [#14](https://github.com/adil192/saber/discussions/14)

<div type='discussions-op-text'>

<sup>Originally posted by @yajo September 15, 2022</sup>
I couldn't find the button!</div>

**Comment by adil192** [comment]
That's because there is no delete button (yet)! I'll accelerate the priority of this for you

**Comment by yajo** [comment]
Lovely, thanks!
