### ISSUE TITLE
Page management

### ISSUE THREAD

**Issue by mdrv** [adil192/saber#151]
It would be nice to have the ability to **change page order**, especially for people who likes to organize (almost) everything in one multi-page note. It could be a separate mode or tool so the UI won’t get cluttered.

I’m using the latest version (v0.4.7) on Android and there doesn’t seem to be any function to reorder the page. My own use case is to put frequently-used or important pages on the top so I can access them more easily.

- [x] Reordering pages
- [x] Duplicating pages
- [x] Deleting pages
- [x] Inserting pages
- [x] Click a page to scroll to it

**Comment by GSTbyMM** [comment]
Page rotation to rotate the vertical pages to horizontal.
