### ISSUE TITLE
Stylus Eraser Support 

### ISSUE THREAD

**Issue by wilkgr76** [adil192/saber#16]
Stylus support is great on my Chromebook; I'd just would love to see the eraser on the pen switching to the stroke deletion tool.

**Comment by adil192** [comment]
Thanks for the report. Unfortunately I currently don't have any devices with a stylus button/eraser, so I'd be coding blind, but I would like to get this feature added.
Please can you tell me the current behaviour of the stylus' eraser: does it write or undo?

**Comment by adil192** [comment]
I assume you're using the Android version on your Chromebook... Please can you install the apk from this release: https://github.com/adil192/saber/releases/tag/v0.3.7-beta1 and tell me if it works?

**Comment by wilkgr76** [comment]
Yes; I'm using the Android app version. The eraser's behaviour is identical to the pen but with a consistent width - I assume the stylus doesn't have pressure sensitivity on the eraser. This same behaviour is also present in the beta version linked.

I'm using a Duet 5 with a Penoval USI 702.

**Comment by adil192** [comment]
Second time lucky? Does [v0.3.7-beta2](https://github.com/adil192/saber/releases/tag/v0.3.7-beta2) work?

**Comment by wilkgr76** [comment]
Nope, unfortunately that doesn't work either. It retains the same behaviour.

**Comment by adil192** [comment]
I think I need to wait until I can get hands-on with a compatible stylus, which will probably be around Christmas time when I come home from uni. I'll keep this issue open in the meantime

**Comment by wilkgr76** [comment]
No worries, wasn't expecting an immediate resolution anyway :)

**Comment by adil192** [comment]
@wilkgr76 Please try this new apk: https://saber.adil.hanney.org/app-release.apk

**Comment by wilkgr76** [comment]
It works! :tada: 

Thank you for the quick turn around, this is awesome!

**Comment by adil192** [comment]
Awesome!

**Comment by yarub123** [comment]
> 

Hey there Adil, apologies for bringing this issue up again. I know it's been brought up a few times. That link you posted no longer works. 
![Screenshot_20230209_193144_Fennec](https://user-images.githubusercontent.com/84487964/217993850-7e024c57-3e69-404a-ab83-c0493b74e9b9.jpg)

**Comment by adil192** [comment]
> > 
> @adil192 
> Hey there Adil, apologies for bringing this issue up again. I know it's been brought up a few times. That link you posted no longer works. 

That was just a testing build, the changes are present in the latest releases

**Comment by yarub123** [comment]
@adil192 Ok makes sense. And damn that was a quick ass reply haha. Thanks again. Hopefully it'll get supported one of these days. Even the latest unfortunately doesn't fix it for me. Other than that, everything works fantastically.

**Comment by adil192** [comment]
@yarub123 You may want to file a bug with Flutter if your stylus' eraser isn't recognised
