### ISSUE TITLE
Unable to login to personal Nextcloud

### ISSUE THREAD

**Issue by darkcodemonkey** [adil192/saber#164]
So far I love the app, so good work. I am trying to login to a self hosted nextcloud server. I tried using the regular url that I have setup and then the username, password and then entering an encryption password, but it says login failed. Due to the fact that I have TOTP setup on my instance and based off of a previous ticket that I saw, I then attempted to login using the https webdav url that is listed in nextcloud (https://example.com/remote.php/dav/files/username/) and the webdav password I have for that access but it still says that the login failed. I have confirmed that I am able to access both the normal nextcloud url that I have setup using the nextcloud app or a web browser, and webdav through both an ios device, and a file explorer and folder sync app on multiple android devices.
Thank you.

**Comment by adil192** [comment]
Are you using an app password instead of your regular password? 
https://docs.nextcloud.com/server/25/user_manual/en/user_2fa.html#using-client-applications-with-two-factor-authentication

**Comment by darkcodemonkey** [comment]
I have tried both my normal password and an app password that I setup through nextcloud.

**Comment by adil192** [comment]
Are you by chance using the web version?

**Comment by darkcodemonkey** [comment]
Nope. Loaded the apk from fdroid (v0.4.9) onto my Galaxy Fold 4 and Galaxy Tab s8+ and when that didn't work I attempted to use 0.5.0 apk from github, which also did not work.

**Comment by njhdunn** [comment]
Are you using a custom SSL certificate authority for your self-hosted nextcloud domain? I had what sound like similar issues connecting to my local nextcloud until I switched it over to using a proper certificate via Let's Encrypt + ACME, after which it worked as expected.

**Comment by darkcodemonkey** [comment]
I am using a Let's Encrypt certificate.

**Comment by dbrandonjohnson** [comment]
I'm running into the same problem trying to login with my nextcloud instance.  Have a letsencrypt cert and using an app password (two-factor is enabled).  I don't get an error when trying to login (I do when I try to use my standard password no tan app passowrd) so it seems like it is authenticating but still shows on the main page that I'm logged out.

**Comment by dbrandonjohnson** [comment]
Looking at the logs from the app (Linux Flatpak in this case)

This is what I'm seeing, but I'm not seeing any error in the app unless I input the wrong password.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NextcloudApiException(statusCode: 401, headers: {}, body: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No public access to this resource., Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, Username or password was incorrect</s:message>
</d:error>
)
#0      WebDavClient._send (package:nextcloud/src/webdav/client.dart:57)
<asynchronous suspension>
#1      NextcloudClientExtension.getConfig (package:saber/data/nextcloud/nextcloud_client_extension.dart:39)
<asynchronous suspension>
#2      NextcloudClientExtension.loadEncryptionKey (package:saber/data/nextcloud/nextcloud_client_extension.dart:59)
<asynchronous suspension>
#3      _NcLoginPageState._tryLogin (package:saber/pages/nextcloud/login.dart:50)
<asynchronous suspension>
#4      _LoginInputGroupState._login (package:saber/components/nextcloud/login_group.dart:87)
<asynchronous suspension>
```

The app password works with other applications.

**Comment by adil192** [comment]
> ```
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NextcloudApiException(statusCode: 401, headers: {}, body: <?xml version="1.0" encoding="utf-8"?>
> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>   <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
>   <s:message>No public access to this resource., Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, Username or password was incorrect</s:message>
> </d:error>
> )
> #0      WebDavClient._send (package:nextcloud/src/webdav/client.dart:57)
> <asynchronous suspension>
> #1      NextcloudClientExtension.getConfig (package:saber/data/nextcloud/nextcloud_client_extension.dart:39)
> <asynchronous suspension>
> #2      NextcloudClientExtension.loadEncryptionKey (package:saber/data/nextcloud/nextcloud_client_extension.dart:59)
> <asynchronous suspension>
> #3      _NcLoginPageState._tryLogin (package:saber/pages/nextcloud/login.dart:50)
> <asynchronous suspension>
> #4      _LoginInputGroupState._login (package:saber/components/nextcloud/login_group.dart:87)
> <asynchronous suspension>
> ```
> 
> The app password works with other applications.

Are you able to connect via WebDAV?

**Comment by dbrandonjohnson** [comment]
> 

Yes, I am able to connect using any webdav client.  Or do you mean using the full webdav url in Saber's settings?

**Comment by adil192** [comment]
> Yes, I am able to connect using any webdav client. Or do you mean using the full webdav url in Saber's settings?

Nah I meant using a webdav client

**Comment by dbrandonjohnson** [comment]
Yes I can use a regular webdav client.

> 
> 
> > Yes, I am able to connect using any webdav client. Or do you mean using the full webdav url in Saber's settings?
> 
> 
> 
> Nah I meant using a webdav client

**Comment by dbrandonjohnson** [comment]
I figured out the problem.  At least for my issue.  My nextcloud instance uses ldap and I just noticed the user data directory is different than what it expects. I'm shocked anything is working on this instance.

So my problem has nothing to do with Saber.  Not sure about the original issuer. 

I'll open a separate issue for a feature request. It would be nice to use a different sync service like seafile or at least just use a generic webdav endpoint.

**Comment by darkcodemonkey** [comment]
Well, I don't have LDAP enabled, so that can be ruled out.

**Comment by darkcodemonkey** [comment]
So I thought I didn't have LDAP enabled, but I must have confused it with something else. I disabled LDAP on my instance and it still says login failed whether I use my normal login info for nextcloud or using the WebDAV URL and app login that I setup for Saber. I am still able to access both my normal nextcloud and WebDAV logins using other applications.

**Comment by adil192** [comment]
> it still says login failed whether I use my normal login info for nextcloud or using the WebDAV URL and app login that I setup for Saber.

You shouldn't be using the WebDAV URL, just the normal Nextcloud URL with the app password

**Comment by darkcodemonkey** [comment]
Same thing when using regular URL and the app password I have setup for saber, login failed.

**Comment by adil192** [comment]
> Same thing when using regular URL and the app password I have setup for saber, login failed.

Are you able to login to Nextcloud Neon (current latest apk at https://github.com/provokateurin/nextcloud-neon/actions/runs/3787903728) and perform actions like creating a folder?

**Comment by darkcodemonkey** [comment]
I am not able to login with this app either... I  get the same desktop user login I get from the normal nextcloud app, put in my username and password and then TOTP it says access granted and then loops back to the login screen again.

**Comment by adil192** [comment]
> I am not able to login with this app either... I  get the same desktop user login I get from the normal nextcloud app, put in my username and password and then TOTP it says access granted and then loops back to the login screen again.

Please can you make a new issue in that repo as it's the plugin I use for Nextcloud? Make sure to reference this issue

Also note that Kate is on holiday at the moment

**Comment by darkcodemonkey** [comment]
I was able to get everything syncing and working properly. IDK if it was a recent change on the app or what, but thank you for the assistance.
