### ISSUE TITLE
Option to Hide Tool bar and file name

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#165]
**Is your feature request related to a problem? Please describe.**
I used to write notes in Android phone in landscape mode bottom and top bar cover a lot of writing area

**Describe the solution you'd like**
There should be option to hide top and bottom bar

**Describe alternatives you've considered**
Not possible

**Device (please complete the following information):**
 - Device: Redmi 9T
 - OS: Android 12L
 - Version: v0.4.9 F-Droid (409)

**Additional context**
![Screenshot_20221225-200511_Saber](https://user-images.githubusercontent.com/84625092/209473251-31544a7c-618e-4ee3-8934-70bd93ba9ab9.png)

**Comment by Luciogi** [comment]
Hi @adil192 , I have tested web version , I felt UX problem , that when user is in full screen mode , changing pen/color can be difficult.
I would suggest to
- add toggle to hide bottom tool bar and top bar(file header) for android users
- web users should have shortcut and toggle both

**Comment by adil192** [comment]
> Hi @adil192 , I have tested web version , I felt UX problem , that when user is in full screen mode , changing pen/color can be difficult. 

I've added a setting for whether to show the toolbar in fullscreen mode.

> Edit: There should be option to move tool bar in vertical position

Please can you make this a separate issue? :)

**Comment by Luciogi** [comment]
sure

**Comment by Luciogi** [comment]
@adil192 I test visibility of toolbar during screen.
It works on Firefox, But not on Brave browser
Have a look at video below

https://user-images.githubusercontent.com/84625092/209701471-ed43d647-e82a-4fe5-b6a4-077b7daa6b32.mp4

**Comment by adil192** [comment]
That's because the web isn't running the latest commits. I usually don't build the web version outside of releases, but I'll update it now for you

**Comment by Luciogi** [comment]
Tested working nicely on web.
