### ISSUE TITLE
Import PDFs as an image background

### ISSUE THREAD

**Issue by privacymatters1** [adil192/saber#17]
I love this app. In particular the feature of synchronising. Great would be the ability to import PDF files and draw on the PDF. As an example if you get in advance the presentation slides of a lecture in university you could mark important parts and write your own ideas direct on the slides.

Depends on #271

**Comment by strk** [comment]
What's the hard part in this ticket, in relation to https://github.com/adil192/saber/issues/183#issuecomment-1400118035 ? Is it not just a matter of converting the PDF to an image ?

**Comment by adil192** [comment]
> What's the hard part in this ticket, in relation to [#183 (comment)](https://github.com/adil192/saber/issues/183#issuecomment-1400118035) ? Is it not just a matter of converting the PDF to an image ?

There's just more moving parts. Converting the PDF to an image looks fairly simple with [pdf_image_renderer](https://pub.dev/packages/pdf_image_renderer). Ideally I'd like to resize each page to match the PDF dimensions which would take some refactoring. Just as a side note, I won't be very active here for a bit since I have exams

**Comment by strk** [comment]
I've tried the background image support and indeed it's much different as it ruins my musical staffs (I guess it's due to changing aspect ratio and the image NOT being vectorial as a PDF would be?).

**Comment by adil192** [comment]
> I've tried the background image support and indeed it's much different as it ruins my musical staffs (I guess it's due to changing aspect ratio and the image NOT being vectorial as a PDF would be?).

Would increasing the maximum image size in settings help with this? Also if aspect ratio is a problem, you can change the background image fit in the editor menu

**Comment by strk** [comment]
On Fri, Feb 03, 2023 at 04:03:29AM -0800, Adil Hanney wrote:

> Would increasing the maximum image size in settings help with this? Also if aspect ratio is a problem, you can change the background image fit in the editor menu

I cannot find that setting, where would I find it ?

--strk;

**Comment by adil192** [comment]
> I cannot find that setting, where would I find it ?

Near the bottom of settings:
![image](https://user-images.githubusercontent.com/21128619/217956289-896c729b-068a-49b0-b6cf-bfb9afb7bbc4.png)

**Comment by strk** [comment]
I had version 0.6.0 this not seeing it. After upgrade I see the setting, but my PNG sheet is 8Kb and the max choice for that setting is 2000 (bytes?) so nothing changes.

**Comment by adil192** [comment]
The maximum is 2000x2000 pixels, how big is your png?

**Comment by strk** [comment]
On Fri, Feb 10, 2023 at 02:11:16AM -0800, Adil Hanney wrote:
> The maximum is 2000x2000 pixels, how big is your png?

835x1181 pixels. Raising the max to 2000 doesn't make the look better
for me. You can find the image here:
http://strk.kbt.io/tmp/blank.png

--strk;

**Comment by adil192** [comment]
Since that's smaller than 2000px, it won't be compressed at all.
Are you by chance talking about the thumbnail on the home screen, since thumbnails are resized to 300px?

**Comment by strk** [comment]
On Fri, Feb 10, 2023 at 09:28:59AM -0800, Adil Hanney wrote:
> Since that's smaller than 2000px, it won't be compressed at all.
> Are you by chance talking about the thumbnail on the home screen, since thumbnails are resized to 300px?

My image is a PNG with size, in pixel, of 835 x 1181

Still the staff lines are not readable. Would an SVG be loadable ?

**Comment by adil192** [comment]
<img src="https://user-images.githubusercontent.com/21128619/219236425-2f6a3f3f-4448-4463-8bde-2f72e0d0b9ea.png" width=500>
Is this what it looks like for you?

**Comment by adil192** [comment]
I'm not sure why that particular image displays incorrectly. It's most likely a Flutter bug.
I've added SVG support in
- #359

**Comment by strk** [comment]
Yes, it looks like the screenshot you sent. Will try the SVG path.

**Comment by strk** [comment]
As of version 0.9.3 I'm happy with the PDF background display, thank you !
