### ISSUE TITLE
Selection/move tool

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#170]
**Is your feature request related to a problem? Please describe.**
There is no option to move content of page

**Describe the solution you'd like**
Add option in tool bar for selection of content on page 

**Describe alternatives you've considered**
I have to remove content  and write again

**Device (please complete the following information):**
- Device: Redmi 9T
- OS: Android 12L
- Version: v0.4.9 F-Droid (409)

**Additional context**
none

**Features**
- [X] Selecting strokes
- [x] Selecting images
- [ ] Duplicate selection
- [ ] Delete selection
- [x] Change color of selected strokes

**Comment by NicholasLam12** [comment]
I think it would also be useful if the selection/move tool is bundled with a copy function so that if you for some reason need two identical diagrams you wouldn't need to redraw the whole diagram again

**Comment by adil192** [comment]
v0.8.0 has a new select tool. It can only move strokes around at the moment but this will be extended in future releases :)

**Comment by Polux49** [comment]
+1 for the duplicate or delete. 
The following actions on the content of a selected area would also be very useful in my opinion: 

- [ ] Stretch it (suggestion: after a long press on the selected area, a box containing it would be convenient for stretching). 
- [ ] By means of the toolbar buttons, change some properties (not only color, but also width and pen style) simultaneously for all the lines in the selected area.

My guess is that you already planned it, but in case of... :-)

**Comment by WasteOfO2** [comment]
You can _technically_ move ur selection to the edges and make it disappear, but i am sure this is more likely to be a bug more than a feature :P

https://user-images.githubusercontent.com/45941793/227790605-5507dd7f-a37c-4623-a1bd-2dd07072ff81.mp4

**Comment by Parameter15** [comment]
Any advance on this?

**Comment by KainAlive** [comment]
In other note-taking apps (GoodNotes, for example), it's possible to select a line by selecting part of it with the selection tool. In Saber, you have to select the whole stroke to move it, which is quite difficult, especially when strokes are close together. It would be nice to be able to select just part of the stroke.

**Comment by adil192** [comment]
> you have to select the whole stroke to move it

@KainAlive The current behaviour is to select a stroke if most (70%) of the stroke is in the selection area. This handles cases where strokes are close together quite gracefully in my testing, such as avoiding the tail of the letter "y" in the line above when selecting something in the line below it. 

https://github.com/adil192/saber/blob/cf91edcbb91869d3b6cbb9081788631dbdc63db3/lib/components/canvas/tools/select.dart#L13-L15

If you'd like this percentage to be configurable by the user (e.g. 0-1% to select any stroke that touches the selection area), please [file a feature request issue](https://github.com/adil192/saber/issues/new?labels=enhancement&template=feature_request.yaml).

**Comment by AdmerStroh** [comment]
I would like to add the ability to not only copy/duplicate the selected content but also to cut it and paste it elsewhere. In addition to the standard dragging around of the selection, this would enable us to move the selection over longer distances (for example a few pages downwards) more easily.

**Comment by AraxTheCoder** [comment]
@adil192 should the duplication, deletion, scaling and cutting menu be accessible by long pressing/right clicking the selection similar to good notes (also in design)?

https://support.goodnotes.com/hc/en-us/articles/7353711532815-Copying-and-pasting-Goodnotes-content

**Comment by adil192** [comment]
> more like the pen tool where the options get shown in the toolbar when the selection tool is selected

I think this would be more consistent with the rest of the app
