### ISSUE TITLE
Jagged strokes on Firefox

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#171]
**Describe the bug**
Pen stroke is not smooth , too much edges and a bit laggy

**To Reproduce**
1. Open firefox
2. Goto https://saber.adil.hanney.org/#/home/whiteboard
3. Use any pen
4. See strokes

**Expected behavior**
Strokes should be smooth  

**Screenshots**
![image](https://user-images.githubusercontent.com/84625092/209528915-28c2a52d-acac-4faa-9fc0-c6f96aa41e16.png)

**Device (please complete the following information):**
 - Device: Laptop
 - OS: Artix Linux
 - Version: Firefox (108.0.1 (64-bit))

**Comment by Luciogi** [comment]
This only happens on firefox not on chromium based browsers

**Comment by adil192** [comment]
You're right, it seems like Firefox isn't updating the mouse position as often

**Comment by Luciogi** [comment]
I have tired other app xournal++_mobile web version it show jagged strokes also there

**Comment by adil192** [comment]
Maybe related to https://github.com/steveruizok/perfect-freehand-dart/issues/9

**Comment by Luciogi** [comment]
@adil192 If you have windows , test there on Firefox

**Comment by adil192** [comment]
Closing as the web version has been deprecated since v0.8.1
