### ISSUE TITLE
Creating a new note re-opens untitled note unless you rename it

### ISSUE THREAD

**Issue by njhdunn** [adil192/saber#173]
**Describe the bug**
When I create a new note from either the 'Home' or 'All Notes' views it creates an untitled note with today's date, e.g. '22-12-26 Untitled'. If I close this note and do not rename it to something else, when I create a new note from either the 'Home' or 'All Notes' views it will re-open the existing untitled note rather than creating a new one.

I observe this behavior on both the Android and Linux versions of the software.

**To Reproduce**
1. Go to the 'Home' or 'All Notes' views
2. Click on the '+' button to create a new note
3. Draw something on the page, and do not rename the note
4. Close the note by clicking the back arrow in the upper left
5. Click on the '+' button again, and the previous note will reopen

**Expected behavior**
The new note '+' button should always create a new blank note with a unique name. If there would be a naming collision the new note should be renamed somehow, perhaps by appending a number to the new note name, e.g. '22-12-26 Untitled 2'.

**Devices:**
 - Device 1: Galaxy Note 9
 - OS 1: Android 12
 - Version 1: 0.4.9 (F-Droid)
 
 - Device 2: Desktop PC
 - OS 2: Ubuntu 22.04
 - Version 2: 0.5.0 (Flathub)

**Comment by adil192** [comment]
Should be fixed with 71d402fc6bea37a0927dfdc8cafabd053dc4fee9 which will be released in v0.5.1
