### ISSUE TITLE
Lock images in place

### ISSUE THREAD

**Issue by yephny** [adil192/saber#183]
**Is your feature request related to a problem? Please describe.**
It's frustrating to draw on images.

**Describe the solution you'd like**
Option to lock / unlock an image in place on a per image basis.

**Describe alternatives you've considered**
Make it so that only a finger can move an image, and that S-Pen can only draw on it.

**Device**
 - OS: Android 10, LineageOS.

**Comment by strk** [comment]
Other alternative: introduce concept of background image which gets automatically stretched to page size and never moves (and there can only be one)

**Comment by adil192** [comment]
@strk Please can you make this a separate feature request?

**Comment by adil192** [comment]
I think a better solution would be to have a separate pen tool and a tool for moving pictures/other things. So when you're drawing, the images won't be interactable.

**Comment by yephny** [comment]
@adil192 That sounds intuitive.

**Comment by strk** [comment]
> @strk Please can you make this a separate feature request?

It sounds like #17 to me

**Comment by adil192** [comment]
> > @strk Please can you make this a separate feature request?
> 
> It sounds like #17 to me

I'm going to add "set as background" as a 4th option in the image dialog
![Screenshot_20230123-102601.png](https://user-images.githubusercontent.com/21128619/214017196-d0a5119a-8415-4c1e-9e1a-9498e7f4f163.png)

# 17 is in regards to PDF imports which is a bit harder

**Comment by strk** [comment]
I'm happy to convert all my PDFs to images if that gets me where I need to go (annotating on sheet music or music paper)
