### ISSUE TITLE
Onyx Boox Support

### ISSUE THREAD

**Issue by ma-con** [adil192/saber#186]
I have long been looking for a cross-platform note taking app, and yours looks really perfect.
I was eager to try it on my Onyx Boox Tab Ultra (an Android 11 based eInk Tablet with Wacom layer) and while it works, writing or drawing is unfortunately quite laggy. I’m pretty sure, that this is because of the device and not your app, as this is also the case for other Android apps. 
I was however wondering, if there is any possibility of improving the experience, as I think the app would be a perfect fit for the Boox devices, To the best of my knowledge, the only working note-taking apps are the included one and Microsoft One Note, both of which don’t allow for self-hosted sync. I’ve read that there is a possibility of integrating a SDK from Boox: https://github.com/onyx-intl/OnyxAndroidDemo/blob/master/doc/Onyx-Pen-SDK.md The app PngNote (https://github.com/karino2/PngNote) integrates this for example.

**Comment by adil192** [comment]
I don't have my Boox Note Air2 with me currently so please can you run this command on your computer with your tablet plugged in for USB debugging:
```bash
adb shell getprop ro.product.vendor.brand
```
or alternatively, run this on Termux on your tablet:
```bash
getprop ro.product.vendor.brand
```

I want to check if it's exactly "onyx" or if it's capitalised differently

**Comment by ma-con** [comment]
It’s all Caps:
```
$ getprop ro.product.vendor.brand
ONYX
```

**Comment by ma-con** [comment]
I’ve seen that you worked on this already, this is really cool, thanks!

If there is anything I can help by testing, please let me know. I currently have a friend’s Nova Air 2 in addition to my Tab Ultra, so I could also test on two different devices with different screen sizes.

Btw: I feel a bit stupid for explaining what the Boox devices are and mentioning the SDK and so after realizing that own one as well and you even contributed to the PNGNote app 😉

**Comment by adil192** [comment]
Sorry about the commits referencing this issue; they reappear every time I rebase the `onyxsdk_pen` branch

**Comment by adil192** [comment]
Finally completed that! You can try out the new version before its official release here: [Build #124](https://github.com/adil192/saber/actions/runs/3871625061)

**Comment by ma-con** [comment]
Thanks a lot, that is really great!
I've just tested it for a few minutes and it worked really well.

I'll certainly test it more in the coming days!
