### ISSUE TITLE
[Android]Only first 2 pages are working

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#188]
**Describe the bug**
Tools does not work on page 3 , also even when portion of page 3 is visible , tools will not work

**To Reproduce**
1. Write on page 1,2 
2. Try to write on page 3

**Expected behavior**
Tools should work all pages

**Screenshots**

https://user-images.githubusercontent.com/84625092/210096151-0325cdb3-403d-42c7-8079-f24a3dd85864.mp4

**Device (please complete the following information):**
 - Device: Redmi 9t
 - OS: Android 13
 - Version: 0.5.1
 - Browser (if applicable):

**Comment by adil192** [comment]
@Luciogi Please can you try the apk from [Build #102](https://github.com/adil192/saber/actions/runs/3808200714) (when it's finished building)?

**Comment by adil192** [comment]
Closing as it's fixed on my end and I want to release the fix quickly. Reopen if not!

**Comment by Luciogi** [comment]
@adil192 Working as expected.
I guess web version is also affected by same issue
