### ISSUE TITLE
Multilingual support, Clear-all button, Theme selection

### ISSUE THREAD

**Issue by Sdarfeesh** [adil192/saber#19]
- [x] Multilingual Support
- [x] Add a button to clear or hold undo button to clear
- [x] Selection for theme (Auto, Light, Dark)

**Comment by adil192** [comment]
Multilingual support is out-of-scope for me as I only speak one language.
The other two sound good

**Comment by Sdarfeesh** [comment]
> Multilingual support is out-of-scope for me as I only speak one language. The other two sound good

I can help for the Chinese Translation

**Comment by adil192** [comment]
> I can help for the Chinese Translation

I'll add multilingual support to the roadmap

**Comment by Triplesweet** [comment]
And for theme, can we have a manual accent color? The accent color right now for me is stuck at a bad orange looking color and I can't change it, a minor inconvenience but would be appreciated

**Comment by mamasch19** [comment]
> 
> > I can help for the Chinese Translation
> 
> I'll add multilingual support to the roadmap

I could help with a German one

**Comment by adil192** [comment]
> I can help for the Chinese Translation

@Sdarfeesh please can you fork this repo, copy `lib/i18n/strings.i18n.json` to `lib/i18n/strings_zh.i18n.json` and edit the English parts to Chinese

> I could help with a German one

@mamasch19 that's awesome, can you do the same but for German `lib/i18n/strings_de.i18n.json`

**Comment by adil192** [comment]
> And for theme, can we have a manual accent color? The accent color right now for me is stuck at a bad orange looking color and I can't change it, a minor inconvenience but would be appreciated

@Triplesweet please can you make this a separate issue :)

**Comment by Sdarfeesh** [comment]
> > I can help for the Chinese Translation
> 
> @Sdarfeesh please can you fork this repo, copy `lib/i18n/strings.i18n.json` to `lib/i18n/strings_zh.i18n.json` and edit the English parts to Chinese
> 
> > I could help with a German one
> 
> @mamasch19 that's awesome, can you do the same but for German `lib/i18n/strings_de.i18n.json`
> 
> Useful links:
> 
> * [`slang`'s Getting Started](https://pub.dev/packages/slang#getting-started)
> * [List of locale codes](https://saimana.com/list-of-country-locale-code/)

These translations are missing,
xould you please replace the word "Login" with "登录"?
https://github.com/adil192/saber/blob/main/lib/i18n/strings_zh.i18n.json#L40
https://github.com/adil192/saber/blob/main/lib/i18n/strings_zh.i18n.json#L56
https://github.com/adil192/saber/blob/main/lib/i18n/strings.g.dart#L423
https://github.com/adil192/saber/blob/main/lib/i18n/strings.g.dart#L555
https://github.com/adil192/saber/blob/main/lib/i18n/strings.g.dart#L689
https://github.com/adil192/saber/blob/main/lib/i18n/strings.g.dart#L706

**Comment by adil192** [comment]
@Sdarfeesh please can I confirm with you that the Chinese translation works in-app?

**Comment by Sdarfeesh** [comment]
> @Sdarfeesh please can I confirm with you that the Chinese translation works in-app?

Works on Android

**Comment by adil192** [comment]
Okay nice thanks

**Comment by adil192** [comment]
Thank you to all our contributors :) I think we can consider this issue complete

**Comment by adil192** [comment]
@Sdarfeesh @mamasch19 @iamjosuefischer @albanobattistella 
Would any of you be interested in being @'ed when new entries to the English translation are added? You're under no obligation to, but please react with a thumbs up if so!
