### ISSUE TITLE
[Web] New page is not visible (Just shadow shows)

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#190]
**Describe the bug**
same as title

**To Reproduce**
1. Go to https://saber.adil.hanney.org/
2. Write something on 1st page
3. Drag to see new page
4. You will see only shadow , not page

**Expected behavior**
Page should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/84625092/210103881-844568a1-6049-4da6-a815-9c040a648046.png)

**Device (please complete the following information):**
 - Device: Desktop
 - OS: Artix Linux
 - Version: 0.5.2 Dirty
 - Browser (if applicable): Firefox

**Comment by adil192** [comment]
I don't experience this on my phone (browser). Perhaps you caught it while v0.5.2 was uploading as there's no v0.5.2 dirty yet.
Please can you try refreshing and trying again?

**Comment by adil192** [comment]
Update: bug only occurs when the page doesn't take up the full screen width (i.e. on desktop)

**Comment by Luciogi** [comment]
I don't know brave browser saved cached version i saw it was 0.5.2 dirty lol.
After New update 0.5.2 Page works but renders shadow as
> Update: bug only occurs when the page doesn't take up the full screen width (i.e. on desktop)
