### ISSUE TITLE
Black rectangle in canvas when in full screen mode

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#195]
**Describe the bug**
Black rectangle appears when full screen mode is activated.

**To Reproduce**
1. Open note
2. Tab on "resize to full screen" icon
3. There is a black rectangle in the canvas.

**Expected behavior**
The black rectangle shouldn't be there.

**Screenshots**
![saber-full-screen](https://user-images.githubusercontent.com/48548230/210151345-03f183e0-d075-4fcf-9270-c9e7504f6d57.jpg)

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab S8
 - OS: Android 13
 - Version: v0.5.1 (Google Play)

**Comment by adil192** [comment]
Is that not just the page divider?

**Comment by adil192** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
>
> 1. Open note
>
> 2. Tab on "resize to full screen" icon
>
> 3. There is a black rectangle in the canvas.

Please can you screen record these steps?

**Comment by Luciogi** [comment]
This is not bug.
How you have created this situation?
 - Go to Settings
    - Enable Dark theme in app
    - Toggle OFF (see below picture)
![image](https://user-images.githubusercontent.com/84625092/210177906-e08a8209-1d62-4721-81c9-344309d9bb01.png)

As that black rectangle is transparent area which is actually page divider

**Comment by adil192** [comment]
Closing as this seems to just be the page divider. If you disagree, please reopen the issue

**Comment by ceskyDJ** [comment]
Oh, you are right, it is just a page divider. I don't know how I could not notice that.
