### ISSUE TITLE
Sometimes note doesn't disappear, when deleted

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#197]
**Describe the bug**
Sometimes when I delete note (on "Home" page), it doesn't disappear immediately.

**To Reproduce**
1. Be on "Home" page
2. Create new note
3. (Draw something)
4. Close the note
5. Delete the note
6. See note is still displayed (with smaller hight)

**Expected behavior**
The note completely disappears.

**Screenshots**

https://cd.wedos.com/s/pkmbN5ajZi8c8P5

**Device:**
 - Device: Samsung Galaxy Tab S8
 - OS: Android 13
 - Version: v0.5.1 (Google Play)

**Comment by ceskyDJ** [comment]
Yes, of course. The video doesn't work directly, so I uploaded to Nextcloud and shared from there. I'll do my best to send it directly here.

**Comment by ceskyDJ** [comment]
https://user-images.githubusercontent.com/48548230/210442239-fd80c648-517e-4e0f-b230-74b5f4782670.mp4

**Comment by ceskyDJ** [comment]
https://user-images.githubusercontent.com/48548230/210457129-15cd7fe6-035e-47d7-a121-2e249aa2755b.mp4

**Comment by fybx** [comment]
@ceskyDJ I had the same issue around v0.5.3, and I assume it got fixed with version 0.5.4. Can you update your installation and then check, please?

**Comment by ceskyDJ** [comment]
> @ceskyDJ I had the same issue around v0.5.3, and I assume it got fixed with version 0.5.4. Can you update your installation and then check, please?

Thanks for additional info, I'll check it again with the newest version installed.

**Comment by ceskyDJ** [comment]
Yes, it works well now.
