### ISSUE TITLE
Whiteboard not working correctly when the left menu is open

### ISSUE THREAD

**Issue by daniarla** [adil192/saber#204]
**Describe the bug**
When the left size menu is open, the whiteboard does not work only the 2 first pages allow writing. 
It looks oddly similar to #188 

**To Reproduce**
Try to use the whiteboard with the left menu open.

**Screenshots**

https://user-images.githubusercontent.com/80422846/210628757-207d645a-360b-4ca8-8670-2bed11c5e6de.mp4

**Device (please complete the following information):**

 - Device: Galaxy tab S6 lite
 - OS: LineageOs 19.1
 - Version: 0.5.2

**Comment by adil192** [comment]
Related to https://github.com/adil192/saber/issues/190
