### ISSUE TITLE
App crashes when use spen button

### ISSUE THREAD

**Issue by shayan15sa** [adil192/saber#208]
Hey, guys. The app crashes when i use s-pen side button to erase.
It also crashes when click on everything on the screen the s-pen button is pressed.

 - Device: [Samsung Tab s6 lite 2022 edition]
 - OS: [Android 13]
 - Version: [v0.5.4]

**Comment by adil192** [comment]
Sadly I can't do much about this. It was first reported in https://github.com/adil192/saber/issues/21 and the upstream issue is https://github.com/flutter/flutter/issues/111068. We're waiting for it to be released in Flutter stable.
Also from my testing, the fix from Flutter's end only stops the crash, but doesn't allow it to work as an eraser (which works with some other styluses).

**Comment by shayan15sa** [comment]
Ok thanks for attention
