### ISSUE TITLE
Font doesn't support Czech diacritics characters

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#212]
**Describe the bug**
Used font for general text doesn't support Czech diacritics characters (like `á`, `é`, `ě`, etc.).

**To Reproduce**
1. Create new note
2. Write text "Příliš žluťoučký kůň úpěl ďábelské ódy"
3. Set text type to monospace and write "Příliš žluťoučký kůň úpěl ďábelské ódy" again
4. See the first string is invalid (letters are corrupted)

**Expected behavior**
Czech diacritics characters are displayed correctly (like in monospace font in screenshot, where is the same text like above - "Příliš žluťoučký kůň úpěl ďábelské ódy" - this is equivalent of English "The quick brown fox jumps over the lazy dog").

**Screenshots**
![tempFileForShare_20230108-221141](https://user-images.githubusercontent.com/48548230/211219579-40cbb0d7-00d9-4d59-b999-7892ee57f706.jpg)

**Device:**
 - Device: Samsung Galaxy Tab S8
 - OS: Android 13
 - Version: v0.5.4

**Comment by adil192** [comment]
Interestingly, this bug happens on Android but not on Pop OS (Linux)

**Comment by adil192** [comment]
![image](https://user-images.githubusercontent.com/21128619/211239074-609804c6-ec6a-4335-a3ce-ae419297169e.png)
I've added a fallback font but it looks a bit jarring

**Comment by adil192** [comment]
![image](https://user-images.githubusercontent.com/21128619/211239912-a17b3199-5608-4f82-89a4-7366cc8bc27c.png)
Better fallback font
