### ISSUE TITLE
Inserting page after active one

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#214]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to insert page between two existing pages. Now, I can't do that at all.

**Describe the solution you'd like**
Add some button to toolbar or something better for inserting new page after the active one.

**Device:**
 - Device: Samsung Galaxy Tab S8
 - OS: Android 13
 - Version: v0.5.4

**Comment by adil192** [comment]
Merging into https://github.com/adil192/saber/issues/151
