### ISSUE TITLE
Navigation Bar on Android is black

### ISSUE THREAD

**Issue by electr1fy0** [adil192/saber#216]
<img src="https://user-images.githubusercontent.com/87616300/211311161-110e1d9d-cdcb-4cbd-ad1a-83370ea5c4ff.png" alt="Screenshot_20230109-181558" width=350>
The bar at the bottom should be transparent and blend in with the rest of the UI like most well designed apps following Material guidelines.

**Comment by Luciogi** [comment]
I guess gesture navigation bar does not have , transparent or blending options, I have not seen any app having this implementation. If you know any app, let us know?

**Comment by electr1fy0** [comment]
What you need:
https://developer.android.com/develop/ui/views/layout/edge-to-edge

Reddit Sync, Google Messages, Twitter,  Google Phone, Files by Google.
(literally any modern app) These either have transparent navigation bars or have colors that are taken from the the region around it.
You can also look at 
![Screenshot_20230112-065233](https://user-images.githubusercontent.com/87616300/211953586-68aa9d8e-08bb-4414-8d2d-43ac161125c0.png)
![Screenshot_20230112-065229](https://user-images.githubusercontent.com/87616300/211953594-244232f4-21d7-452e-b214-9b73eb363f8c.png)

**Comment by adil192** [comment]
> What you need: https://developer.android.com/develop/ui/views/layout/edge-to-edge

Thanks for the link :)
