### ISSUE TITLE
Choose max image size

### ISSUE THREAD

**Issue by minnten** [adil192/saber#218]
if I import an image, it es rapidly downscaled, so that all necessary informations get lost.

**To Reproduce**
1. Open a note
2. import an image
3.  Scale it to fit the page

**Expected behavior**
It would be perfect, if I could select the quality of the imported picture, to use the image as background until the PDF-background function is avaliable.

**Screenshots**
the Image i wanted to import:
![3 Seite](https://user-images.githubusercontent.com/50588960/211404844-9c34be59-6e3e-4758-b287-bc9003960d78.png)

A Screenshot from the image inside Saber:
![Bildschirmfoto vom 2023-01-09 21-47-21](https://user-images.githubusercontent.com/50588960/211405808-2541060e-4b10-4568-9dc0-f1b9374913ac.png)

**Device (please complete the following information):**
 - Device: Laptop or Galaxy Tab Active PRO
 - OS: Arch Linux or Android 11
 - Version: v0.5.4

**Comment by adil192** [comment]
I've added a setting to change how much images are compressed
