### ISSUE TITLE
Non-FOSS in F-Droid build

### ISSUE THREAD

**Issue by licaon-kter** [adil192/saber#219]
Since https://github.com/adil192/saber/issues/186 you've [added some libs](https://github.com/adil192/saber/blob/e71fb5ced94089407cf7807db97227461d46b56b/packages/onyxsdk_pen/android/build.gradle#L59-L60) that I can't find their source code and they are not hosted in any of the [F-Droid trusted repos](https://gitlab.com/fdroid/fdroidserver/-/blob/4ce2f291e311ade59b51b257e3fa9f0e34735be7/fdroidserver/scanner.py#L439-L458)

Is the Onyx SDK even FOSS?

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/9a8e215a9b2e42d454c41dbe7b3d4fe00edaa12e

**Comment by adil192** [comment]
I've added a script to remove the Onyx SDK. MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12397
