### ISSUE TITLE
Lock/Disable Zoom

### ISSUE THREAD

**Issue by ma-con** [adil192/saber#220]
When using the app with a stylus, I often unintentionally zoom the canvas, especially on a small device. I guess this comes from my wrist resting on the tablet when writing with the stylus which is somehow misinterpreted as a gesture.

Maybe it would be possible to add an option to disable zooming by either an option in the preferences or a toggle in the toolbar?

**Comment by fybx** [comment]
I +1 this issue as well. Pretty annoying on Xiaomi Pad 5; even with palm rejection, my tablet seems to accept any touch input, making it very hard to write anything for 5 seconds without accidentally zooming in.
