### ISSUE TITLE
APK size

### ISSUE THREAD

**Issue by yephny** [adil192/saber#234]
The apk seems to have grown quite a bit in size, to 80 MB from 20s. Could there be something unwanted bundled in v.0.5.5?

**Comment by adil192** [comment]
The extra size is due to the Onyx SDK for https://github.com/adil192/saber/issues/186. Currently, you could get a smaller apk by downloading the F-Droid build which comes without the Onyx SDK. 

I'll distribute a FOSS apk in the future (i.e. without the Onyx SDK)

**Comment by yephny** [comment]
Thanks, though I see a 40MB of difference even on F-Droid.

**Comment by adil192** [comment]
Oh that's unexpected, I'll look into that

**Comment by adil192** [comment]
Even completely removing the onyx stuff gives me an apk with size 65.6MB

**Comment by adil192** [comment]
https://github.com/adil192/saber/blob/bb078023602d5d2b52342cc51479716326eb5268/android/app/build.gradle#L58

Changing this line back to `minSdkVersion 18` gives an apk of 30.5 MB

**Comment by adil192** [comment]
Since the FOSS apk doesn't use the Onyx SDK, I reduced its minSdkVersion to 18 and its resulting size is 30.5 MB. I'll add it to the v0.5.5 release

**Comment by yephny** [comment]
Thanks!

**Comment by adil192** [comment]
Following up on the Flutter issue, Saber will be sticking to the Android default.

> Android has chosen to opt for faster load times and larger download size.

If anyone coming across this wishes to override this, add this to `android/app/build.gradle`:
```gradle
android {
    packagingOptions {
        // Use legacy convention of compressing all .so files
        jniLibs.useLegacyPackaging true
    }
}
```

**Comment by yephny** [comment]
Is the Flutter version being bumped up the reason for the latest size increase?

**Comment by adil192** [comment]
@yephny
 
The size increase in v0.11.0 is because the minSdkVersion was raised back to 23

The small size increase in v0.11.4 is because fonts are now bundled into the apk to avoid an anti-feature on F-Droid (#572)
