### ISSUE TITLE
Allow dirty build installation with different app id

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#242]
**Is your feature request related to a problem? Please describe.**
Testing dirty builds is difficult , when stable version is installed. Switching back and forth is pain

**Describe the solution you'd like**
Installation of dirty builds/artifacts with different id.

**Describe alternatives you've considered**

**Device (please complete the following information):**
 - Device: Redmi 9t
 - OS: Android 13
 - Version: 0.5.5

**Additional context**
none

**Comment by adil192** [comment]
Resolved with https://github.com/adil192/saber/commit/599f2e1850ff397613b07fef0bf0623746312dc4

**Comment by Luciogi** [comment]
@adil192 `Saber-Android-FOSS-Alt.zip` is not actually zip file. 
![image](https://user-images.githubusercontent.com/84625092/213524743-ca9f640a-939b-4b2b-a029-c33642935dd1.png)

**Comment by adil192** [comment]
> @adil192 `Saber-Android-FOSS-Alt.zip` is not actually zip file. 
> ![image](https://user-images.githubusercontent.com/84625092/213524743-ca9f640a-939b-4b2b-a029-c33642935dd1.png)
> 

It's working for me. Your download might be corrupted, try downloading it again

**Comment by Luciogi** [comment]
@adil192 thanks
