### ISSUE TITLE
URL validation fails with IP address/port

### ISSUE THREAD

**Issue by brahimjarallah** [adil192/saber#247]
**Unable to authenticate to a selfhosted nextcould local server!! it said "Please enter a valid URL"**

**Steps to reproduce the behavior:**

1. Go to 'setting'
2. Click on 'Tap to log in with nextcloud'
3. check 'I want to use a custom Nextcloud server'
4. enter a local nextcloud server url , nextcloud email, nextcloud password and nextcloud new app encryption password.
5. See Error "Please enter a valid URL" even if all credentials are correct !

**I hope you solve this issue to make authentification possible to our selfhosted nextcloud server and allow "Saber" to be syncronizable with nextcloud.**

**Screenshots**
![Screenshot_20230118_184113](https://user-images.githubusercontent.com/52374652/213255478-a8c9c548-784a-4b6a-b286-f3abc4af0dea.jpg)

**Device**
 - Device: [mobile/tablet]
 - OS: [Android 9]]

**Comment by brahimjarallah** [comment]
Please try to fix this bug ASAP! 
and thanks for your great efforts 👍🏻

**Comment by adil192** [comment]
As a side note, you've accidentally revealed your encryption password. I recommend that you change it after the fix is released.

**Comment by adil192** [comment]
You can try the new changes before the next release here: https://github.com/adil192/saber/actions/runs/3953159315
