### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by yephny** [adil192/saber#25]
I'm not sure if the app fits the requirements of F-Droid, but do you think you could have Saber included in F-Droid? It would surely boost its popularity, while supporting libre software.

**Comment by daffydock** [comment]
It is already on F-Droid.

**Comment by yephny** [comment]
Yes, I'm talking about the main repository where apps are built by F-Droid.

**Comment by adil192** [comment]
Writing this here as proof I support this app being on F-Droid and my GitLab account is https://gitlab.com/adil192

**Comment by yephny** [comment]
Thanks!

**Comment by adil192** [comment]
Merge request into the F-Droid repo: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11947

**Comment by adil192** [comment]
Now live at https://f-droid.org/en/packages/com.adilhanney.saber/ (though the icon is missing for some reason)

**Comment by yephny** [comment]
Great news.
