### ISSUE TITLE
Nextcloud account not saved on macOS 

### ISSUE THREAD

**Issue by ma-con** [adil192/saber#257]
After happily using Saber on my Onyx Boox Android devices, I also installed it on my MacBook to be able to view the notes there. I sync my notes using my own nextcloud server and everything works fine until I close saber. After restarting Saber it shows "Logged out" in settings and I have to add the account again, then everything works fine until the next restart. 

**To Reproduce**
1. Add nextcloud account in macOS app.
2. Close and restart app
3. Account is logged out

**Expected behavior**
Account details should be saved across restarts.

**Device (please complete the following information):**
 - Device: MacBook Pro 2021
 - OS: macOS 13.1
 - Version: 0.5.7

Thanks for the amazing app!

**Comment by adil192** [comment]
> `/Users/runner/work/saber/saber/macos/Runner.xcodeproj: error: "Runner" has entitlements that require signing with a development certificate. Enable development signing in the Signing & Capabilities editor. (in target 'Runner' from project 'Runner')`

Looks like this won't work without an Apple Developer account, so we'll need to wait until I meet [my sponsorship goal](https://github.com/sponsors/adil192)

**Comment by adil192** [comment]
https://github.com/adil192/saber/blob/ef24a5a4d43fe9b9148672279b0d2519667c9dc7/lib/i18n/strings.i18n.json#L107-L112

You'll be able to opt-in to insecure storage in the next update (or in [this](https://github.com/adil192/saber/actions/runs/3971850333) beta build)

**Comment by adil192** [comment]
I'm going to close this since keychain sharing should work on the App Store. Please track the App Store issue for more info
- #464

Thank you for your patience
