### ISSUE TITLE
While using the Stylus/S-pen on Samsung Tab S6 lite the hand leaves marks

### ISSUE THREAD

**Issue by ywa4you** [adil192/saber#259]
**To Reproduce**
- Start taking notes with a stylus
- Rest your hand on the tablet
- Locate marks upon raising the hand

**Expected behavior**
- No marks left by hand(or an option to be toggled on)

**Screenshots**
![IMG_20230120_224037](https://user-images.githubusercontent.com/94799005/213810388-7ff62626-1a95-45f6-b89b-6db8a1e52b07.jpg)
![IMG_20230120_224056](https://user-images.githubusercontent.com/94799005/213810457-eb33cb00-a1f9-454c-bef1-3b347e952305.jpg)
![IMG_20230120_224102](https://user-images.githubusercontent.com/94799005/213810492-e64aeaf7-b6bf-4cab-ade8-473c2154e174.jpg)

**Device:**
 - Device: Samsung Tab S6 lite (SM-P610)
 - OS: LineageOS 19/Android 12
 - Version: 0.5.6

**Comment by adil192** [comment]
Palm rejection is handled by Samsung. However, you can turn off drawing with your hand 
![image](https://user-images.githubusercontent.com/21128619/213812930-1f7195f2-3a39-45de-83fd-35b1c50c4095.png)

**Comment by ywa4you** [comment]
Damn, my bad. Thank you very much. Now I can daily drive this thing at school using only foss software.
