### ISSUE TITLE
Garbled text on Mac 10.12.6

### ISSUE THREAD

**Issue by mattdrepo** [adil192/saber#26]
The app doesn't display fonts properly on Mac 10.12.6

![saber](https://user-images.githubusercontent.com/69482750/193109722-099001f4-4c24-4cff-abb6-6d05bb2776cd.png)

https://github.com/authpass/authpass/blob/6a835981e32b1e7bb17a59dea1c7cd59cb05ada8/authpass/lib/theme.dart#L86-L102

**Comment by adil192** [comment]
It seems like Flutter only supports macOS 10.13 and up https://github.com/flutter/flutter/issues/57805. I'll look into adding a third-party font but other things might also not work as expected on 10.12.

**Comment by mattdrepo** [comment]
Thank you for trying.  There was a resolve in the github issue i linked you to.  If you get a good resolve then this could be used for others also using flutter as I have seen this issue on another app (spotube) which also has this problem.  I think this particular operating system, although EOL, is quite a poignant release on Mac OS as it supports the use of 32 bit mac x86 apps well.  And FOSS keeps it alive.

**Comment by adil192** [comment]
@mattdrepo Please can you try running this build: https://github.com/adil192/saber/actions/runs/3289360417

**Comment by mattdrepo** [comment]
nearly done, nextcloud login has some garbled text, and new note...

![nextcloud login](https://user-images.githubusercontent.com/69482750/197001248-d37b947c-7662-4976-84fb-3407630ea2af.png)
![new note](https://user-images.githubusercontent.com/69482750/197001258-91091607-43e5-4938-b7fc-8b3bfb56b73d.png)

**Comment by adil192** [comment]
> ![new note](https://user-images.githubusercontent.com/69482750/197001258-91091607-43e5-4938-b7fc-8b3bfb56b73d.png)

please can you explain a bit more about what's wrong in the editor?

**Comment by mattdrepo** [comment]
i presumed the _6dy04 was gibberish, might of been randomly generated info.  Forgive if wrong!

**Comment by adil192** [comment]
yep that's just a randomly generated name! I'd be happy to change how they're generated if you can think of a better format (I don't want other people thinking it's gibberish!)

**Comment by adil192** [comment]
> ![nextcloud login](https://user-images.githubusercontent.com/69482750/197001248-d37b947c-7662-4976-84fb-3407630ea2af.png) 

note to self: looks like slang's rich text is using its own font

**Comment by mattdrepo** [comment]
how about date, time - unix format with "New Note" appended last.  Encouraging someone to rename it. But of course keeping it unique

**Comment by adil192** [comment]
I think I prefer "Untitled" over "New Note"
<img src="https://user-images.githubusercontent.com/21128619/197022455-a08fddd5-cb97-47ef-84e7-22fc320a258d.png" alt="Untitled" width=300><img src="https://user-images.githubusercontent.com/21128619/197022585-9f9aa07b-19fa-4b42-91e1-a11713a770bf.png" alt="New Note" width=300>

**Comment by adil192** [comment]
Should be fixed with [v0.3.12](https://github.com/adil192/saber/releases/tag/v0.3.12)

**Comment by adil192** [comment]
Hi @mattdrepo, does Saber still run on macOS 10.12.6?

> Flutter 3.3 is the last stable release with macOS 10.11 through 10.13 best-effort support.
