### ISSUE TITLE
Allow HTTP connections for custom Nextcloud server

### ISSUE THREAD

**Issue by mr-scientific** [adil192/saber#267]
**Is your feature request related to a problem? Please describe.**
I run my own private nextcloud instance, and use an HTTP since the connection is already encrypted using tailscale. When I try connecting saber to my server, it trys adding 'https://' to the url even it has the 'http://' prefix causing the connection to fail. Of course doing it without the prefix tries to make it an https connection, also causing it to fail.

**Describe the solution you'd like**
I would like the app to enable support for http connections. I get that it isn't secure, so maybe add a warning saying that instead? If this is not possible, I would like an alternative method to connect to my nextcloud instance.

**Describe alternatives you've considered**
1. Use the default nextcloud server.
- This doesn't work since I write a lot of notes for my classes and I'll use the available storage quickly.
2. Not syncing notes
- Not ideal since syncing would help

**Device (please complete the following information):**
 - Device: Primarily a Samsung S6 Lite
 - OS: Stock Android 12
 - Version: 0.5.7 (the current latest version in f droid)

**Additional context**
If there is an existing way to do this, I'm more than happy to try it out, I just haven't found it myself.

I'd like end by saying thank for the amazing app, apart from this issue, everything else has worked incredibly well. I also understand if for some reason or the other that this request isn't possible.

**Comment by adil192** [comment]
Please try v0.5.8 when it gets released on F-Droid

**Comment by mr-scientific** [comment]
Ok, I will. Thank you for implementing this!

**Comment by adil192** [comment]
Just to follow up, have you had a chance to try out the new update yet?

**Comment by mr-scientific** [comment]
Yes, I didn't realise the update released. I tried it now and it seems to work fine. Thanks for the awesome work!
