### ISSUE TITLE
[Suggestion] IOS and MacOS App Publishing

### ISSUE THREAD

**Issue by ramazansancar** [adil192/saber#270]
Have you had the opportunity to review the following link regarding your application publishing process on iOS and MacOS?

- https://developer.apple.com/support/membership-fee-waiver/

**Comment by adil192** [comment]
Yes I'm unfortunately not eligible

> Fee waivers are not available for:
> 
> - Organizations distributing paid apps or apps with in-app purchase on the App Store.
> - Members of the Apple Developer Enterprise Program.
> - Individuals and sole proprietors/single-person businesses.
