### ISSUE TITLE
Toggle buttons too wide on small screens

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#279]
**Describe the bug**
I tried to install Saber to my phone, too (I need to sync notes there for sometime reading). When I opened settings, I found a little problem with text wrapping, could you look at it, please?

**To Reproduce**
1. Go to app settings on smaller mobile.
2. Open 1st and 3rd categories.
3. See problems with text wrapping.

**Expected behavior**
Text is wrapped word-by-word (and so much better readable), not char-by-char. In some situations, the UI may be more responsive (wide switch needs a lot of space on mobile...)?

**Screenshots**
<img src="https://user-images.githubusercontent.com/48548230/215325158-1c17c35e-a71d-401d-99ad-1511bd4c7b2b.jpg" alt="Comparison toggle buttons" width=300> <img src="https://user-images.githubusercontent.com/48548230/215325161-752c1981-4f2e-468c-9459-ca78d08d2cc6.jpg" alt="Toggle buttons are too wide" width=300>

**Device:**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Version: v0.5.8

**Comment by adil192** [comment]
Please can you visit the nightly web build at https://adil192.github.io/saber/#/home/settings on your S9 and check if the problem is fixed?

**Comment by ceskyDJ** [comment]
> Please can you visit the nightly web build at https://adil192.github.io/saber/#/home/settings on your S9 and check if the problem is fixed?

Yes, of course. I would say it is ok now.
