### ISSUE TITLE
Syncing not working. File has 0b size

### ISSUE THREAD

**Issue by Hedronmx** [adil192/saber#283]
Hello! First of all I love your app and it's design. I appreciate your time and effort.

Just want to report that I can't get sync to work. I can login onto my nextcloud and the saber folder is created. But when I create a new note, it gets uploaded to the server with 0b size. I suppose it's got no data.

Even though there's a new file in the folder, I can't see the note on any other device.

I tried creating a note on my phone, tablet or PC and none of those notes get sync. I also deleted the folder several times, as well as logging in with a app password and my personal password with no results.

Please let me know what I should do. Thank you so much

I have attached a screenshot of my saber folder inside nextcloud

![Screenshot_20230201-002547](https://user-images.githubusercontent.com/26935602/215989947-db92b3fd-79a3-4559-a831-6078445e87a8.png)

**Comment by mr-scientific** [comment]
I have a similar issue. I did some testing and it seems to delete stuff even locally upon syncing with the server. My guess would be it sees that the server does not have a copy of the file and deletes it locally to match. Fortunately I exported some of my notes as PDFs, but I did lose some. 

if it helps I use a custom next cloud instance (the snap version). I'm also currently using the latest build on F-Droid which is 0.8.0

**Comment by adil192** [comment]
> My guess would be it sees that the server does not have a copy of the file and deletes it locally to match. 

This should hopefully be fixed with https://github.com/adil192/saber/commit/b78e4e0a911f67ec57d395a270fc8e1ec9dbb1eb following https://github.com/provokateurin/nextcloud-neon/commit/658ad9f26b64102e2c00d4de36d4dc45428d2aa9

**Comment by adil192** [comment]
@Hedronmx Are you able to upload files with [Nextcloud Neon](https://github.com/provokateurin/nextcloud-neon/blob/main/packages/neon/README.md)? You can find the current latest apks here: https://github.com/provokateurin/nextcloud-neon/actions/runs/4108587515

**Comment by Hedronmx** [comment]
> @Hedronmx Are you able to upload files with [Nextcloud Neon](https://github.com/provokateurin/nextcloud-neon/blob/main/packages/neon/README.md)? You can find the current latest apks here: https://github.com/provokateurin/nextcloud-neon/actions/runs/4108587515

Negative, 0b file as well

**Comment by adil192** [comment]
In that case I would recommend moving this issue to https://github.com/provokateurin/nextcloud-neon

**Comment by Freeedim** [comment]
Hi there,

I have the same problem with newly installed Android v0.12.5 and Flatpak v0.12.6.

I don't know what Nextcloud-neon is.

Is there any update or workaround that would enable me to synchronise my notes?

**Comment by adil192** [comment]
@Freeedim [Nextcloud Neon](https://github.com/provokateurin/nextcloud-neon) is the project which Saber uses to connect to Nextcloud. If your server doesn't work with the APK from [nextcloud-neon's latest build](https://github.com/provokateurin/nextcloud-neon/actions/runs/5017104488), then there's either a problem with your server configuration or you can make a bug report in that repo.
