### ISSUE TITLE
UI and editor got extremely laggy with recent updates (>0.5.4)

### ISSUE THREAD

**Issue by fybx** [adil192/saber#293]
**Describe the bug**
From 0.5.5 and especially on 0.7.0, all the interface seems to get lag spikes (like you would get in an online FPS game). These lag spikes and unresponsiveness happen randomly, which differs from what was described in #179. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on any button or widget; there will be a lag with a chance of 50%
2. Open any note or the whiteboard. Start writing, and it will get unresponsive moments that span up to 3 seconds

**Expected behaviour**
A fluent experience throughout the UI and when writing.

**Screenshots**
I can't provide any, but I will add them as soon as possible.

**Device (please complete the following information):**
 - Device: Xiaomi Pad 5 and Xiaomi Redmi Note 8 Pro
 - OS: Android 12 on Pad 5, Android 11 on Redmi
 - Version: 0.7.0

**Comment by fybx** [comment]
Every visible delay is also present when not screen recording, so it's definitely not a hardware problem.

https://user-images.githubusercontent.com/41127439/216296741-75fbe6eb-6a5d-4439-acf3-489ed9cc16cc.mp4

**Comment by HishamAHai** [comment]
The linux version installed from flathub is also very laggy and unresponsive

**Comment by fybx** [comment]
This issue is resolved out of the blue now. Probably because of the improvements in Flutter itself, so I'm closing it
