### ISSUE TITLE
Flickering in and out of fullscreen

### ISSUE THREAD

**Issue by Sdarfeesh** [adil192/saber#295]
**Describe the bug**
↑ Title

**To Reproduce**
1. Open a note or white board
2. Click full screen

**Expected behavior**
Full screen enabled without flickering

**Screenshots**

https://user-images.githubusercontent.com/50188628/216296987-16a5cc6d-3988-4f99-aa23-ba3ef49233a8.mp4

**Device (please complete the following information):**
 - Device: Alldocube iPlay 20
 - OS: Android 12
 - Version: v0.8.0

**Comment by fybx** [comment]
Same here with Xiaomi Pad 5 w/ Android 12:

https://user-images.githubusercontent.com/41127439/216297618-c6605006-9ef9-430c-aebe-4d5087bc3d03.mp4

**Comment by adil192** [comment]
Looks like the behavior was changed (fixed) in Flutter 3.7 so my hack is no longer valid
