### ISSUE TITLE
Apple Pencil on ipad

### ISSUE THREAD

**Issue by aniteshreddy** [adil192/saber#298]
I have installed this application on my IPad using AltStore.
When I’m trying to use Apple Pencil it doesn’t recognize it instantly, even tough it recognizes the pencil and shows watermark along the pencil trail but it doesn’t write on the screen. I have to keep pencil in the screen for quite sometime to start writing. For every word this has to be repeated.

IPad os 16
Apple Pencil 2

**Comment by adil192** [comment]
I don't understand what you mean by the watermark. Please can you share a screen recording?

**Comment by aniteshreddy** [comment]
https://user-images.githubusercontent.com/43822146/216573201-c38372be-85ef-42f7-bc36-0d701cc5eebc.MP4

As you can see in the video. Pencil is recognized but, it won't write on the screen those lines appear while my pencil is moving on the screen. (I called them watermark).

**Comment by adil192** [comment]
Does the same occur on the web version? https://adil192.github.io/saber/#/home/whiteboard

**Comment by aniteshreddy** [comment]
This doesn't happen on web version however, sometimes pencil is not at all recognized and the pressure sensitivity is not working on the web version.

**Comment by NineXYZ** [comment]
I have the same problem with the Apple Pencil 1, except that I can't even write letters, it only lets me make lines.

**Comment by adil192** [comment]
> As you can see in the video. Pencil is recognized but, it won't write on the screen those lines appear while my pencil is moving on the screen. (I called them watermark).

https://github.com/flutter/flutter/issues/120478 might fix this

**Comment by adil192** [comment]
A fix was released in [Flutter 3.7.5](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#375-feb-22-2023)

> This hotfix release addresses the following issues:
> - https://github.com/flutter/flutter/issues/119180 - Apple pencil writes on Flutter apps instead of scrolling when outside of a text field.

Please can you try out this build: https://github.com/adil192/saber/actions/runs/4252785096

**Comment by NineXYZ** [comment]
Sorry for the late response!
I can confirm (at least on my device) that the bug is gone in the latest release.
