### ISSUE TITLE
Themed monochrome icon

### ISSUE THREAD

**Issue by HotarunIchijou** [adil192/saber#299]
Right now the application doesn't support themed icon. So I want it to be here

**Comment by adil192** [comment]
Depends on
- https://github.com/mrrhak/icons_launcher/issues/12

**Comment by HotarunIchijou** [comment]
@adil192 but can't you add the icon without this tool?

**Comment by adil192** [comment]
Yes but it's a lot easier with the tool. I've forked the tool to add this functionality anyway:
- https://github.com/mrrhak/icons_launcher/pull/28

**Comment by HotarunIchijou** [comment]
Yeah, perfect now
