### ISSUE TITLE
Flickering in and out of fullscreen

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#308]
**Describe the bug**
I opened Saber on my phone after some time (the last version I tried was 1.6.*) and it immediately started lagging.

**To Reproduce**
1. Open Saber app on phone
2. See lagging behavior

**Expected behavior**
I need smooth experience. This is unfortunately unusable.

**Screenshots**

The best way how to get what is happening is just watch this short video (other apps are ok):

https://user-images.githubusercontent.com/48548230/216779053-12798175-979c-4e8c-aa6e-22d8fc9111ba.mp4

**Device:**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Version: v0.8.0 (Google Play)

**Comment by ceskyDJ** [comment]
Maybe there is some connection with #293.

**Comment by ceskyDJ** [comment]
It does the same thing on my Samsung Galaxy Tab S8 (Android 13, v0.8.0 from Google Play), when:

1. Open Saber
2. Go to settings
3. Scroll down
4. Take screenshot using Samsung tools (Screen write or Screen select)
5. Cancel creating screenshot
6. Lagging starts

**Comment by ceskyDJ** [comment]
Hmm, the behavior is similar to #295 but this time is does it everywhere (regardless the full screen mode).

**Comment by adil192** [comment]
This should be fixed by https://github.com/adil192/saber/commit/8245c284a0b44251cc7d050e743e02d3d39a2837
