### ISSUE TITLE
F-droid update are delayed

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#320]
**Is your feature request related to a problem? Please describe.**
As application causing some breakage(Full screen flicker bug). So Hotfixes arrives too late through Fdroid pipeline 

**Describe the solution you'd like**
Consider Trying [IzzyonDroid](https://apt.izzysoft.de/fdroid/index/info) 

**Describe alternatives you've considered**
none
**Device (please complete the following information):**
 - Device: Redmi 9T
 - OS: Android 13
 - Version: 0.8.0

**Additional context**
IzzyOnDroid directly can use prebuilt binary from Repository releases

**Comment by adil192** [comment]
Seems like a duplicate of https://github.com/adil192/saber/issues/146

**Comment by Luciogi** [comment]
I read that that it was removed from by IzzyonDroid. May be uploading to izzyondroid under different application id and logo to avoid signature mismatch

**Comment by Luciogi** [comment]
Or would it be possible to add similar signature to Saber-FOSS.apk throught github releases. (I guess user could manually update without signature conflict) Correct me

**Comment by Luciogi** [comment]
@adil192 I enabled fdroid unstable updates, I am to get early updates
