### ISSUE TITLE
Remember if zoom lock is enabled

### ISSUE THREAD

**Issue by fybx** [adil192/saber#330]
**Is your feature request related to a problem? Please describe.**
No, I find it annoying to always toggle the zoom lock.

**Describe the solution you'd like**
A settings menu entry to get zoom lock enabled by default for every open file & the whiteboard.

**Describe alternatives you've considered**
:) Using my fingers

**Device (please complete the following information):**
Not applicable

**Additional context**
Not applicable

**Comment by adil192** [comment]
Similar to #370, I'll make it so that the last-used state is persisted.
