### ISSUE TITLE
Have versioning info in names of release artifacts

### ISSUE THREAD

**Issue by fybx** [adil192/saber#331]
**Is your feature request related to a problem? Please describe.**
I'm working on an Arch Linux User Repository package for Saber, and artifacts provided in GitHub releases do not contain version information that can make packaging for AUR easier.

**Describe the solution you'd like**
I thought about providing a pull request to the GitHub action you set for "Build for Linux" but got lost easily. Anyways, I found this workflow: https://github.com/marketplace/actions/github-releases-for-automated-package-publishing that provides variables to utilize the version name in the action itself, such that it would enable us to rename the artifacts generated.

**Describe alternatives you've considered**
Not applicable

**Device (please complete the following information):**
Not applicable

**Additional context**
I will try again with what we currently got in hand when I have the time.

**Comment by adil192** [comment]
Would renaming them from e.g. "Saber-Archive" to "Saber-v0.9.1-Archive" be sufficient?

**Comment by adil192** [comment]
With b3b2e9969fcfb447af04356e519d8b1aa8582dae I've renamed e.g. `Saber-Linux-Portable.tar.gz` to `Saber_v0.9.1_9010.tar.gz`.
Does this fix your issue?

**Comment by fybx** [comment]
Yes, it does. Thanks!
