### ISSUE TITLE
Navigation bar background

### ISSUE THREAD

**Issue by xmha97** [adil192/saber#343]
Hi, the dark mode is on.
Why the navigation background is white?

![Screenshot_2023-02-13-17-32-35-272_com.adilhanney.saber.jpg](https://user-images.githubusercontent.com/23485114/218478683-fdfa3380-a4ab-4d4c-a1da-c7ef18240bf5.jpg)

**Comment by adil192** [comment]
Does your navbar change colours in other apps?
