### ISSUE TITLE
Change colors of selected object

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#357]
**Is your feature request related to a problem? Please describe.**
_same as title_

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Device (please complete the following information):**
 - Device: Redmi 9T
 - OS:  Android 13
 - Version: 0.8.0 F-droid

**Additional context**

**Comment by adil192** [comment]
I'm going to combine this into the older selection issue
- Duplicate of #170
