### ISSUE TITLE
Pick a new name for the line height option

### ISSUE THREAD

**Issue by ModcoLocko** [adil192/saber#371]
-Pixel 6A
-Android 13
-Version 0.9.2

The default font size is really small, and it would be convenient to just be able to change what the default font size is in layout settings.

**Comment by adil192** [comment]
![Screenshot_20230219-181708](https://user-images.githubusercontent.com/21128619/219967181-c920ec77-f6aa-4a70-bae2-68cd66ebfe95.png)

You can change the text size with this "line height" option. After this, your last-used line height will be set as the default for new notes.

I do agree that the name needs to be changed to reflect how it affects the text tool

**Comment by hamRS** [comment]
What About Font Size ? 
![Screenshot 2023-02-25 162505](https://user-images.githubusercontent.com/43479443/221375712-a244fe82-0529-47a2-b56c-57a120768139.png)
