### ISSUE TITLE
Last change isn't saved

### ISSUE THREAD

**Issue by Sdarfeesh** [adil192/saber#379]
**Describe the bug**
The last change of note or whiteboard isn't saved

**To Reproduce**
1. Go to any note or whiteboard
2. Do any changes (Draw, erase, clear, etc)
3. Go to another page

**Expected behavior**
The last change should be saved

**Screenshots**

https://user-images.githubusercontent.com/50188628/220313691-47202fba-09aa-4497-8000-7f834b2b9ded.mp4

**Device (please complete the following information):**
 - Device: Alldocube iPlay 20
 - OS: Android 10
 - Version: v0.9.3

**Comment by Iey4iej3** [comment]
I can reproduce this issue under v0.12.8 in the following way:

1. Create a new notebook (by pressing "+");
2. Write something;
3. Wait for less than 7 seconds, say;
4. Tapping "←" to close.

Then the new notebook is not saved. On the other hand, if we wait more than 10 seconds, then the notebook is saved. This is a serious bug, which would lead to great loss of notes.

There is a seemingly probable explanation: only the "autosave" function is working to save notes. According to https://github.com/adil192/saber/commit/484e7405165f04141f44ffa041123e041c0b718c, currently, the autosave interval is set to be 10 seconds, which is consistent with the above observation.

Suggestions for solutions: when the user press "←", or minimizing the APP, or whatever to close the current note, the opened note should be saved.

**Comment by Iey4iej3** [comment]
The commits https://github.com/adil192/saber/commit/4b39bd52318bb009b54ca81541b18aefd98b59c6 and https://github.com/adil192/saber/commit/3bd5aee9c806e709a0f3dd9309e97a09b214a5ae might be relevant. Let's see whether this is fixed in the next release.

**Comment by Iey4iej3** [comment]
The last change of notes is saved in the current build (v0.12.10), with a notification on saving. The last change of whiteboard is not saved, without notification.

**Comment by adil192** [comment]
Thanks for your report @Iey4iej3 I'll see if I can fix this before the next release
