### ISSUE TITLE
Can't sync on custom nextcloud server

### ISSUE THREAD

**Issue by markwmuller** [adil192/saber#382]
**Describe the bug**
I'm trying to use this on two android devices, and my linux laptop. I am logging into my own private nextcloud instance (works fine) on multiple devices. I expect notes to sync, but they don't. I see the folder appear on nextcloud, and then each new note I make seems to create a new file in the folder (with gibberish encrypted title). I notice there are a few similar posts, but they don't seem to quite match what I have. Notably: 
1. The files have size >0B, so I don't think it's the same as https://github.com/adil192/saber/issues/283
2. I've deleted the "Saber" folder on Nextcloud, and deleted all data from the app (as suggested in https://github.com/adil192/saber/issues/118 ). When logging in again, a new folder is created, and everything proceeds as before. 
3. I've done the above when logging in with my nextcloud username, and as my email (as per https://github.com/adil192/saber/issues/118#issuecomment-1343352418 ). 
4. (edit to add): The sync animation spins for a second or two, but then stops, so I don't think it's the same as https://github.com/adil192/saber/issues/143

Is there any way I can see info on what's happening to try and debug (or other suggestions)? 

**Device (please complete the following information):**
 - Device:
   - Laptop, Ubuntu 22.04 (Saber latest from flatpak, v0.9.3 (9030).
   - Android tablets, Android 13, both v0.9.3 Google Play (9030)

**Comment by AdmerStroh** [comment]
+1 for this issue.
The files get uploaded to my selfhosted nextcloud, but do not get recognized/downloaded by the other clients. As OP described, neither deleting the Saber folder on the nextcloud nor resetting the clients seem to help. @adil192 Please advise how to get some useful logs to aid fixing this problem. Maybe @markwmuller solution could already help to develop a fix?

Tested with the flatpak package and two Android 13 devices with version 0.12.10.

Thank you!

**Comment by adil192** [comment]
@markwmuller Please can you test out 1f919fb462b7f5f206c1cb2f53c8ddad9ddfc381?

**Comment by markwmuller** [comment]
> @markwmuller Please can you test out [1f919fb](https://github.com/adil192/saber/commit/1f919fb462b7f5f206c1cb2f53c8ddad9ddfc381)?

Sorry, but I no longer use this, and don't have the capacity to test this.

**Comment by adil192** [comment]
No worries

**Comment by AdmerStroh** [comment]
@adil192 Hey, unfortunately I still cannot get my own Nextcloud to work with sync. With your instance, sync works just fine. I know there must be an issue on my side, but is there anything special to configure on a fresh nextcloud instance to make sync work?

Kind regards

**Comment by AdmerStroh** [comment]
As an additional note: with my own nextcloud instance, all clients can successfully upload notes but the all cannot download/read the notes that other clients uploaded to the Saber folder.

**Comment by adil192** [comment]
> but is there anything special to configure on a fresh nextcloud instance to make sync work?

Mine is pretty much a stock install, I've not configured much except the theming and removing some apps that I don't need.

> they all cannot download/read the notes that other clients uploaded to the Saber folder

Are they uploading to one universal Saber folder or their own user account's Saber folder? Saber can only sync to one user account's Saber folder

**Comment by punithrudrappa** [comment]
I'm facing the same issue. I really love your project. Can you please help me with this.
It syncs to nextcloud. But changes doesn't get reflected in other devices.

**Comment by QubaB** [comment]
I am observing problem that some files are not synchronized from nextcloud. 
In the log file is:

> flutter: SEVERE: FileSyncer: Failed to download file /Škola/BF/3. cvičení/7.22.sbn2 (Saber/f10b4c04e90a32b20ac0f13121ea34f501817d1a11a1fc47969053421301fd6ef3fe1609a7bbbe.sbe): Invalid argument(s): Invalid or corrupted pad block

_Invalid or corrupted pad block_  is probably caused by decryption of file (It is probably downloaded, bud decrypter fails). I am trying to investigate it now.

Can you @punithrudrappa post log file?

**Comment by punithrudrappa** [comment]
How to get logs? I didn't any such option in docs or in the app settings.

**Comment by QubaB** [comment]
> How to get logs? I didn't any such option in docs or in the app settings.

Which OS do you use?

I am working on nextcloud synchronization log directly in Saber now, because I think it is important to know about synchronization issues.

**Comment by punithrudrappa** [comment]
Mac, android, ios

**Comment by QubaB** [comment]
Try youtube and search for "android logcat viewer". I have no experience with Mac and ios.

I am using Windows (there it is easy to obtain logs running Saber from console: _Saber.exe > log.txt 2>&1_) and AndroidStudio for Saber development so I have easy access to logs.
