### ISSUE TITLE
Allow to translate "Untitled" when creating a new note

### ISSUE THREAD

**Issue by diego-mrqs** [adil192/saber#388]
**Is your feature request related to a problem? Please describe.**
When creating a new note, the default title is "YY-MM-DD Untitled", in all languages. 

**Describe the solution you'd like**
Add a way to translate "Untitled" to other languages. For instance, in Portuguese this should be "Sem título".

**Device:**
 - Device: PC
 - OS: Fedora
 - Version: v0.9.4

**Comment by adil192** [comment]
If you want, I can add "Sem título" without you needing to make a pull request?

**Comment by diego-mrqs** [comment]
> If you want, I can add "Sem título" without you needing to make a pull request?

Yes, no problems.

**Comment by ceskyDJ** [comment]
@adil192, is it hard to add support for modifying datetime format (or just automatically load default format for OS selected locale)?

**Comment by diego-mrqs** [comment]
@ceskyDJ 

Although here the date format is DD-MM-YYYY, I like the current one (YYYY-MM-DD) because it keeps the notes (and files in general) sorted by creation date in a file manager.

**Comment by ceskyDJ** [comment]
> @ceskyDJ
> 
> Although here the date format is DD-MM-YYYY, I like the current one (YYYY-MM-DD) because it keeps the notes (and files in general) sorted by creation date in a file manager.

You are right. Do, @adil192, it is not one of good ideas :D.
