### ISSUE TITLE
Weird PDF appearance in Dark Mode

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#400]
**Describe the bug**

When using dark mode, the PDF pages no longer maintain their original appearance and makes it inconvinient to annotate on them.

**To Reproduce**
1. Enable dark mode
2. Add grid lines/ any page layout other than blank
3. Load a PDF
4. Observe the bug

**Expected behavior**

Expected to load the PDF with it's original appearance and without the background of the page being visible.

**Screenshots**

Here is how it looks like in Saber

![Screenshot_20230223-030826_Saber](https://user-images.githubusercontent.com/45941793/220775382-0d63d94e-9ca2-4922-aa8a-231f16f09085.png)

Here is what the original PDF looks like

![IMG_20230223_060725](https://user-images.githubusercontent.com/45941793/220795934-2695290e-80fc-4813-bc12-0c5e9ea96a60.jpg)

Here is a reference of how One Note handles it

![Screenshot_20230223-061038_OneNote](https://user-images.githubusercontent.com/45941793/220796266-acca64c5-4b39-498a-b663-bbcf1a6758cc.png)

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab S6 Lite LTE
 - OS: Lineage OS 19-20230121-NIGHTLY-gta4xl
 - Version: v0.9.4(9040)
 - Browser (if applicable): -

**Comment by adil192** [comment]
This is because notes are inverted in dark mode. You'll notice that if you write something in black text over the pdf in OneNote, it will be white in light mode and be really hard to read.

You can turn inverting off globally in Settings:

![image](https://user-images.githubusercontent.com/21128619/220800366-77738259-efa6-4cb9-8a74-803836b547dd.png)

or you can configure it per image (for background images. you first need to remove them as a background using the menu) by long pressing the image (or right clicking on desktop):
![image](https://user-images.githubusercontent.com/21128619/220800779-4f4277d0-dbdb-4c44-b110-039e7ed6a394.png)

**Comment by adil192** [comment]
PS: The pdf itself has a transparent background. You can just turn off the background pattern if needed

**Comment by WasteOfO2** [comment]
Thx for the response.

I do want to note that it isnt practical for me to constantly switch themes.

I prefer having dark theme with grids when I write my notes, and switch to the default appearance of the PDF, similar to how my One Note is set up as shown above.

I have tried other PDFs from various sources and the issue was reproducible on my end. I am not aware how common it is for PDFs to have transparent backgrounds.

Would it be possible to instead load the PDFs as opaque images? If we could figure out a way to perhaps convert singular PDF pages into JPEGS or smth.

**Comment by adil192** [comment]
How's this?
![image](https://user-images.githubusercontent.com/21128619/220884654-fbf00fc8-b826-4328-aa5a-e00ab153b192.png)

**Comment by WasteOfO2** [comment]
Thx! That is exactly whaat I was looking for! This would apply to PDFs too I assume?

**Comment by adil192** [comment]
> Thx! That is exactly whaat I was looking for! This would apply to PDFs too I assume?

yep, I updated the description to reflect that

**Comment by WasteOfO2** [comment]
Sweet. Sorry for so many requests, but would it be possible to add an option to not apply auto dark mode to images? It sometimes makes text and info to not be very legible.

Here is how it looks like in Saber

![Screenshot_20230223-205221_Saber](https://user-images.githubusercontent.com/45941793/220950323-ca6616ea-2990-4e8f-8292-ff4ffc5a0cc7.png)

Here is how it looks like in a PDF viewer

![Screenshot_20230223-205135_MJ PDF Reader](https://user-images.githubusercontent.com/45941793/220950686-454fcba7-8e72-4aae-b88f-5b98e7f66df2.png)

**Comment by adil192** [comment]
Yeah no worries, just make a new issue for it so I don't forget!

The blurry image is definitely something I need to look into... Does it look the same in light mode?

**Comment by WasteOfO2** [comment]
Hey, i have opened another issue here https://github.com/adil192/saber/issues/400 as u asked
