### ISSUE TITLE
Better color chooser for pens

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#418]
**Is your feature request related to a problem? Please describe.**
Your color picker is a bit weird for me. There are 5 customizable slots and some predefined. I think the predefined color palette is fine but the second one works a little different I would expect.

**Describe the solution you'd like**
When I choose one of predefined colors, it shouldn't change any of the first 5 slots. These slots should be user-defined (it could already be done using packed detailed color picker, it's very good) and maybe it should be preserved between notes and whiteboard. At least, choosing of predefined color shouldn't touch these 5 slots.

**Describe alternatives you've considered**
I don't know what you or other users think about it. So, when anyone has own opinions, feel free to start a discussion in this issue. I would like to read other points of views, too.

**Device:**
 - Device: Samsung Galaxy Tab S8
 - OS: Android 13
 - Version: v0.9.4

**Additional context**
![tempFileForShare_20230225-153554](https://user-images.githubusercontent.com/48548230/221363446-5b2f0640-ae1b-4034-a0f8-635296893e31.jpg)

**Comment by WasteOfO2** [comment]
I think the first 5 slots are intended for custom colours, although I do agree that the behaviour is weird

**Comment by ceskyDJ** [comment]
> I think the first 5 slots are intended for custom colours, although I do agree that the behaviour is weird

Oh, here is a little misunderstanding. I'm 100% happy with customizing the first 5 slots. I hate only current behavior, just like you (as I understand your comment) and I would like to see chosen colors staying the same, so I don't need to find just the right color I need there for every note (I have some "standard" colors I use almost time).

**Comment by WasteOfO2** [comment]
So u need a colour palate that can be saved?

**Comment by ceskyDJ** [comment]
> So u need a colour palate that can be saved?

It would be so good :D, but at least it shouldn't have current weird behavior (as I described above).

**Comment by adil192** [comment]
The first five slots were intended to be your recently used colors, although I can see how this might not line up with expectations now that there's a custom color picker

**Comment by adil192** [comment]
The first five slots were intended to be your recently used colors, although I can see how this might not line up with expectations now that there's a custom color picker

**Comment by ceskyDJ** [comment]
As you says, it acts more like a weird behavior. I think it should not change at least after picking color from the right slot. These colors are permanently visible, so they haven't to be in displayed twice. But as I wrote before, the best would be bigger remake of the color picker tool.

**Comment by adil192** [comment]
I've added a setting for you
