### ISSUE TITLE
donate button in crypto

### ISSUE THREAD

**Issue by dzmitry-lahoda** [adil192/saber#422]
**Is your feature request related to a problem? Please describe.**
i cannot donate via paypal or librepay.

**Describe the solution you'd like**
Add any crypto address onto page or app so I can send crypto.

**Describe alternatives you've considered**
not donating

**Comment by adil192** [comment]
I don't have a crypto wallet or anything like that so I can't accept donations in crypto at this time. Thanks for your consideration :)
