### ISSUE TITLE
Remove the S Pen warning on first start

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#426]
The bug mentioned in flutter which causes S pen button interactions has been fixed and in my experience causes no issues

https://github.com/flutter/flutter/issues/111068

![Screenshot_20230228-110036_Saber](https://user-images.githubusercontent.com/45941793/221763027-22246432-59a3-4fdd-950c-a749b731a313.png)

I think it should be safe to re-add the eraser functionality with the S Pen button, willing to test functionality on my device for the same

**Comment by adil192** [comment]
Thanks for reminding me about this, that warning is outdated.

> I think it should be safe to re-add the eraser functionality with the S Pen button

Unfortunately there is nothing to re-add. The Flutter team fixed the crash but the s pen button still does nothing

**Comment by WasteOfO2** [comment]
I will link the relevant flutter issue here for reference for the buttons not working

https://github.com/flutter/flutter/issues/42846

This specific comment in the issue linked above caught my eye (still an upstream issue, not related to saber)

https://github.com/flutter/flutter/issues/42846#issuecomment-1114369971

**Comment by adil192** [comment]
You can probably just use the logs from running Saber in debug mode (i.e. with `flutter run`) with some print statements added to event listeners.
But for contributing to Flutter, you should ask on the issue you linked
