### ISSUE TITLE
Allow imported PDF to be centered on page

### ISSUE THREAD

**Issue by m0byn** [adil192/saber#430]
As written in the title, the option to center the imported PDF on the page would be very helpful! Then, one could annotate on the left side too!

**Comment by WasteOfO2** [comment]
Can you show a screenshot of what you mean?

**Comment by adil192** [comment]
Are the background fit options what you're looking for?
![image](https://user-images.githubusercontent.com/21128619/222122851-53e96726-bcc3-48fc-9e15-c2bfcd122f42.png)

**Comment by m0byn** [comment]
Oh well... I tried a different PDF just now and found out that it acutally works as desired! Apparently, the used PDF has a large right margin, so it looked like not centered...so this thread can be closed. Thank you! Keep up the great work it is an amazing app!
