### ISSUE TITLE
Allow zooming below 1.0x

### ISSUE THREAD

**Issue by m0byn** [adil192/saber#431]
It would be very helpful if negative zoom would be allowed. Then, one could zoom out and see two or three pages to get a better overview. Also, scrolling through pages would be faster. Of course, I am aware of the "pages" feature to scroll faster. However, just to zoom out to display two or three pages would be very helful!

**Comment by WasteOfO2** [comment]
A better title could be "Allow zooming below 1.0x"

Also, just a request to follow the Feature Request template given to you

**Comment by m0byn** [comment]
Edited the title just now. 
Ok, I will do that in the future - thank you for mentioning it!
