### ISSUE TITLE
Export Notes as PDF or other formats

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#434]
**Is your feature request related to a problem? Please describe.**

Sometimes I want to be able to locally save my notes in a format readable by other apps, or when I want to share it with others

Referenced in https://github.com/adil192/saber/issues/429

**Describe the solution you'd like**

Saber should be able to export a note as a PDF(for example), where 1 in Saber corresponds to 1 page
in the PDF

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab S6 Lite LTE
 - OS: Lineage OS 19.1
 - Version: v0.9.5

**Additional context**
Apps like Notability and (to a limited extent) One Note allow to export my notes as PDF

**Comment by adil192** [comment]
Use the export button (share icon) in the toolbar
