### ISSUE TITLE
Willing to help with documentation/wiki

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#438]
It has been great to use Saber. It went from an app constantly crashing cuz of my S Pen a few months back to _almost_ being feature complete as of today(for me atleast)

I want to give back to this project by helping the way i know it best. I have contributed to some linux and linux-related wikis in the past. This is going to be a new type of project for me but i do feel like a lower barrier for entry any project is always welcomed.

willing to discuss it in this issue here or move it to Discussions!

**Comment by diego-mrqs** [comment]
I think it is a nice idea. I can help to develop the documentation and translate it to PT-BR. 

However, I think maybe it is better to do this just when the app is close to a stable release.

**Comment by WasteOfO2** [comment]
The earlier we start, the more ready and polish it will be by the time stable hits.

If i had to make a guess, we _might_ hit stable within 2-3 months. Last few releases will probably take longer, however, Adil can show better light at this

**Comment by ceskyDJ** [comment]
Oh, it grows up here :D. I can help, too (at least sometimes) and translate your work into Czech.

**Comment by WasteOfO2** [comment]
@adil192 friendly ping, thoughts?

**Comment by adil192** [comment]
I don't really know what goes into writing a wiki so I probably can't be of much help.
But I've gone ahead and enabled a publicly editable [wiki](https://github.com/adil192/saber/wiki)

**Comment by WasteOfO2** [comment]
The wiki will have stuff like contributing guidelines, common issues, FAQs, roadmap, current features, etc

Would especially help lower barrier of entry for new devs if the code itself could be documented. Example how PDFs are rendered, how settings are applied, common directories which saber uses, etc etc

These are just a few things from the top of my head, i am sure as more ppl chime in, we can get more stuff done.

It is for u and us to decide what goes in, but we do need pointers from u for what u want documented

**Comment by WasteOfO2** [comment]
@adil192 , sorry for multiple pings as of late. Waiting for ur input. Would be nice if u can subscribe to this issue.

We can otherwise move this to discussions
