### ISSUE TITLE
PDF export as vector graphics

### ISSUE THREAD

**Issue by minnten** [adil192/saber#445]
**Is your feature request related to a problem? Please describe.**
I wanted to export a note and afterwards the resolution was really bad.

**Describe the solution you'd like**
Export the PDF-File as a vector-graphics, not as pixel-graphics. 
This will increase the scalability of the PDF and could perhaps shrink the file-size of the PDF.

**Describe alternatives you've considered**
There is the sbn-Export, which exports the json, perhaps you could reintegrate the Array to a *.svg-like format which could be transfered to PDF.

**Device (please complete the following information):**

1. Device: Fujitsu U9311X, OS: Linux (Arch), Version: 0.9.6 (AppImage)
2. Device: Samsung Galaxy xCover 5, OS: Android 13, Version: 0.9.5 (F-Droid)
3. Device: Samsung Tab Active Pro, OS: Android 11, Version: 0.9.5 (F-Droid)

**Additional context**
Picture of Saber-Content:
![image](https://user-images.githubusercontent.com/50588960/223440753-43bf563e-08f3-4d86-b5b4-5d2abc5cbcd5.png)

Picture of the PDF:
![image](https://user-images.githubusercontent.com/50588960/223441312-6b810449-4628-4058-933f-05aa8040a71c.png)

Picture of the PDF zoomed to 800%:
![image](https://user-images.githubusercontent.com/50588960/223442258-a6048959-1422-4729-899e-ec1958ecc2ba.png)

**Comment by adil192** [comment]
PDFs used to use vector graphics until v0.8.0 with this commit https://github.com/adil192/saber/commit/5a8bfdabb08ce36355e1314a53303d1446ed3af0 (see its commit message for the reason).

I've now changed this so that strokes use vector graphics and everything else is just a screenshot.
