### ISSUE TITLE
Improve whiteboard icon

### ISSUE THREAD

**Issue by iamjosuefischer** [adil192/saber#46]
### Discussed in #45 (deleted)

<div type='discussions-op-text'>

<sup>Originally posted by **iamjosuefischer** October 26, 2022</sup>
I think the whiteboard icon that is used at the moment It is not related to its functionality, I suggest a new icon for the whiteboard that is more linked to its functionality to improve the UI design and experience. You should try the Draw Icon to replace it:

### **Draw Icon**
**Google Font URL:** https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Adraw%3A
**Flutter ID:** `draw_outlined`
<br>
Requested by: @iamjosuefischer to @adil192 for Saber.</div>

**Comment by adil192** [comment]
Thanks :)
