### ISSUE TITLE
Get Saber on the App Store

### ISSUE THREAD

**Issue by adil192** [adil192/saber#464]
This issue will track the process of getting Saber on the App Store for iOS and macOS.

- [X] Purchase developer account
- [X] Fill in details about Saber
- [X] Upload the iOS/macOS binaries to the App Store from GitHub Actions
- [X] Create a Saber account with demo notes
- [X] Get access to a macOS device
- [X] Setup [auto_screenshot](https://pub.dev/packages/auto_screenshot) to take screenshots (d588cfce7b1775bca61b890ebd9c50118012c4fe)
- [X] Manually take screenshots because the iOS simulator wasn't picking up the `apple-app-site-association` file
    - &#x2612; <s>Wait for Apple CDN to pick up my `apple-app-site-association` file</s>
    - &#x2612; <s>Take screenshots with auto_screenshot `dart run auto_screenshot`</s>
- [X] Submit Saber for review (iOS)
- [X] Remove macOS workaround from https://github.com/adil192/saber/issues/257
- [X] Submit Saber for review (macOS)
- [X] Wait for review
- [X] Get Saber on the App Store (macOS)
- [X] c5b14f5cc78301fd7259140c45c0db17ed8dab60 Open the sign-up page in-app on iOS
- [X] Get Saber on the App Store (iOS)

**Comment by adil192** [comment]
[Demo.zip](https://github.com/adil192/saber/files/10952788/Demo.zip)

**Comment by yoann-chaperon** [comment]
I downloaded the zip and dezipped it but I can't open the "Saber" application.  :(
saber is available on appstore ?

**Comment by adil192** [comment]
@yoann-chaperon Do you get an error message? Also I assume you're on macOS?
And no Saber isn't on the App Store yet

**Comment by yoann-chaperon** [comment]
yes I am on macos and when I launch saber I get the message "Unable to open the "Saber" application."

**Comment by adil192** [comment]
@yoann-chaperon Which macOS version are you on?

**Comment by adil192** [comment]
It might have something to do with you using an M1 chip, but unfortunately I don't know how I could debug/fix that

**Comment by WasteOfO2** [comment]
Is it possible to run it under Rosetta Stone or smth? Idk i dont use macs

**Comment by WasteOfO2** [comment]
> The application “Saber.app” can’t be opened. “Saber.app” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware. **Move To Trash** or **Cancel** on macOS 13.2.1 (mac mini 2020)
> 
> App Sandbox: Enabled Hardening: Not enabled Notarization: None detected Gatekeeper: Can't evaluate Signed By: Can't verify signature
> 
> I've made a [homebrew script](https://github.com/BingoKingo/homebrew-bingokingo/raw/main/Casks/saber.rb) for saber, you can try `brew install bingokingo/bingokingo/saber`

Is there a setting in macos to run apps from unknown sources?

**Comment by WasteOfO2** [comment]
@adil192 if u have capable hardware (a midrange laptop should be fine), u could look into running mac os in a vm

https://github.com/Coopydood/ultimate-macOS-KVM

**Comment by adil192** [comment]
> The application “Saber.app” can’t be opened. “Saber.app” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware. **Move To Trash** or **Cancel** on macOS 13.2.1 (mac mini 2020)
> 
> App Sandbox: Enabled Hardening: Not enabled Notarization: None detected Gatekeeper: Can't evaluate Signed By: Can't verify signature

This is covered in the installation instructions:
> macOS will warn you that the app is from an unidentified developer when you first open it, so you'll need to go to System Preferences > Security & Privacy and click Open Anyway.

<br>
<br>

> 
> I've made a [homebrew script](https://github.com/BingoKingo/homebrew-bingokingo/raw/main/Casks/saber.rb) for saber, you can try `brew install bingokingo/bingokingo/saber`

> url "https://github.com/adil192/saber/releases/download/v#{version}/Saber_v#{version}_#{version.minor}0#{version.patch}0.app.zip"

Just giving you a heads up that this url scheme will only work if `version.patch` is a single digit. 
E.g. for v0.11.10 the version code would be `(11)(10)0` without the brackets.
Also when we reach Saber v1.0.0 the version code will be `(1)(00)(00)0` without the brackets.

**Comment by adil192** [comment]
> @adil192 if u have capable hardware (a midrange laptop should be fine), u could look into running mac os in a vm, should help with debugging, qemu does have arm in their cpu architecture, so it might work
> 
> https://github.com/Coopydood/ultimate-macOS-KVM

I'll look into this, thanks

**Comment by WasteOfO2** [comment]
> > @adil192 if u have capable hardware (a midrange laptop should be fine), u could look into running mac os in a vm, should help with debugging, qemu does have arm in their cpu architecture, so it might work
> > https://github.com/Coopydood/ultimate-macOS-KVM
> 
> I'll look into this, thanks

I will note, 3D acceleration is not available(or rather, terrible for our use case) without passthrough, the guide has covered passthrough as well. MacOS isnt exactly meant to be virtualized, so be warned

**Comment by adil192** [comment]
Moving discussion about the macOS app not opening to
- #591
