### ISSUE TITLE
[Severe] New update completely breaks zooming and scrolling

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#465]
@adil192 
**Describe the bug**

Zooming on or scrolling between pages doesnt work

**To Reproduce**
1. Open a new or existing note
2. Upon zooming, it focuses only on a specific corner. Scrolling does nothing.
3. See error

**Expected behavior**

Expected zoom and scroll to function as they did in previous versions

**Screenshots**

https://user-images.githubusercontent.com/45941793/224569748-25f5e043-bec0-4a90-86fb-6aed9a0057cd.mp4

Screencap is only using my fingers, not stylus

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab S6 Lite LTE
 - OS: Lineage OS 19-20230121-NIGHTLY-gta4xl
 - Version: v.0.9.7
 - Browser (if applicable): -

Downgrading doesn't work. Do not try to uninstall and reinstall older versions, current notes WILL be lost

**Comment by minnten** [comment]
I have the same issue on my Laptop with 0.9.7 as an Appimage

**Comment by adil192** [comment]
Thanks for the bug report!
