### ISSUE TITLE
Paste images from clipboard

### ISSUE THREAD

**Issue by adil192** [adil192/saber#470]
**Is your feature request related to a problem? Please describe.**
I'm writing this issue on behalf of my friend.
To import an image, you first need to save it to a file and then import it. I'd like to be able to paste images taken using the Windows Snipping Tool which are just saved to the clipboard.

**Describe the solution you'd like**
Press Ctrl-V to paste from the clipboard.

**Describe alternatives you've considered**
Saving to a file and then importing into Saber. I'd prefer not to clutter up my files.

**Device (please complete the following information):**
 - Device: HP Elite X2
 - OS: Windows 11
 - Version: v0.9.8

**Comment by WasteOfO2** [comment]
Other OS can save images to clipboard as well. Is this feature only planned for Windows?

Linux Wayland can utilize the `wl-clipboard` package for smth similar. Not sure abt iOS, Android or Mac

**Comment by adil192** [comment]
As always, I'll try to support as many platforms as possible

**Comment by WasteOfO2** [comment]
Sure, the principle of reading clipboards is the same across probably. Perhaps the actual implementation might differ.

Friend's issue should probably take priority :P
