### ISSUE TITLE
Only straighten a line if it's already roughly straight

### ISSUE THREAD

**Issue by smellymoo** [adil192/saber#499]
**Describe the bug**
The logic for detection of intention to draw a straight line is totally broken. It seems to be "if you hold your finger in one place for a set time". The problem is if you are slowly tracing out a design, then it clears it all and replaces it with a single line.

**To Reproduce**
1. touch_down.
2. draw one continuous line.
3. pause in one spot for a second or 2.
4. cry as your design is wiped and replaced with a line.

**Expected behaviour**
it should only detect a straight line if either:
- you have not strayed from that line path by much (best option).
- you start by pausing after touch_down (easier to code).

**Device (please complete the following information):**
- Device: samsung xcover pro 2
- OS: android 13
-  Version: 0.9.6

## Tasks
- [X] Create a function to calculate the straightness of a line #510
- [ ] Only straighten a line if it's already roughly straight

**Comment by WasteOfO2** [comment]
If i were u, i would disable the line detection. Drawing and stuff like that dont require line detection(generally). It can be re-enabled when u need it.

Although, my handwriting is bad enough that it sometimes turns my writing into lines (T_T)

**Comment by smellymoo** [comment]
think the simpler fix might be better to add now:

you start drawing a straight line by pausing only after touch_down (easier to code). If you get more than a certain distance from the mouse down within the initial delay, don't do a straight line.

**Comment by adil192** [comment]
This would break the way users expect to use this function, so I'll just do the other solution

**Comment by WasteOfO2** [comment]
Sometimes line detection acts up when i dont want it to, as i stated above with my handwriting, but this is not easily reproducible.

However, line detection should not act when the fugure is obviously not a straight line or somewhat representative of it

https://user-images.githubusercontent.com/45941793/227786207-cccbc57b-4cdf-453a-9fb4-1001b3204180.mp4
