### ISSUE TITLE
failed to log in although login information is correct

### ISSUE THREAD

**Issue by ramardoautistin** [adil192/saber#500]
**Describe the bug**
i'm trying to log into my account from my linux computer and my samsung tablet and both devices fail to log in. i'm using my username, the nextcloud password i just created, and the app password i generated on the website. not sure if i'm using the wrong encryption password? or if it's a server/app issue that prevents me from logging in.

**To Reproduce**
1. input login information.
2. click on login.
3. error: "login failed. please check your details and network connection."

**Expected behavior**
a successful login :c

**Screenshots**
![image](https://user-images.githubusercontent.com/128057719/227782701-db123f3c-10da-4efa-8f72-5633456fed39.png)

**Device**
computer: Lenovo (all in one) running elementaryOS 7
tablet: Samsung Galaxy Tab A7 Lite

**Comment by adil192** [comment]
You choose your encryption password when you first log in to Saber.
Your nextcloud password is the app password.

Please keep this issue open for now so I can add this to the FAQ on the login page

**Comment by ramardoautistin** [comment]
so that was the problem!! i would have never realized myself lol, thank you so much.
