### ISSUE TITLE
Incorrect positioning of dots in pdf export

### ISSUE THREAD

**Issue by toobaz** [adil192/saber#514]
**Describe the bug**
When exporting to pdf, dots are often out of place.

**To Reproduce**
1. Create a new note
2. In the first page, draw any stroke
3. Scroll down to the second page
4. Draw a dotted circle where some dots are actual dots while others are actually lines
5. Export to pdf

**Expected behavior**
The dots and the strokes in the circle do not align - they don't even come close. In some more complex notes, dots even appear in the wrong page.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1224492/228476489-0c8cbbaa-b5c5-4014-bac2-545af0e5af84.jpg" width=300> <img src="https://user-images.githubusercontent.com/1224492/228476791-440929d1-9f4e-4c31-a460-a90fd40f64b3.png" width=300>

First: screenshot while drawing. Second: screenshot of the resulting pdf.

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab SM-T585
 - OS: Android 8.1.0
 - Version: 0.1.11 from Google Play (9080), but also 0.9.8 (9110)

Notice I could _not_ reproduce with version v0.9.6 from F-Droid (9060) on a Pixel 4a running LinageOs 19.1 (Android 12). But I can't rule out this was luck - the bug does not happen _every_ time (it still does in most of my tests).

**Comment by WasteOfO2** [comment]
Reproduced with more complex notes, is it specific only to dots or other figures as well? I have no reason to think they would be treated differently. Tested on version 0.9.11


![Screenshot_20230330-102115_Saber](https://user-images.githubusercontent.com/45941793/228733910-b183e100-99ac-4ff8-9331-27126ac3ddac.png)
![Screenshot_20230330-102828_MJ PDF Reader](https://user-images.githubusercontent.com/45941793/228733912-f732eea3-df76-465b-b564-eecc98ef0b7e.png)

Here, i remember i drew the periodic table and moved it outside the page, but it still shows up

![Screenshot_20230330-103540_Saber](https://user-images.githubusercontent.com/45941793/228735077-661fb193-8c0b-4e7e-a046-ebb4b602c178.png)
![Screenshot_20230330-103620_MJ PDF Reader](https://user-images.githubusercontent.com/45941793/228735081-db3b4515-f800-4083-9061-b59e0a7ed294.png)

Also notice how carbon nitrogen cycle is messed up too

![Uploading Screenshot_20230330-103807_MJ PDF Reader.png…]()

**Comment by toobaz** [comment]
> is it specific only to dots or other figures as well?

I experienced this only with dots, and since I'm regularly converting long, complex notes to pdf and I only got this problem with dots I would tend to rule out that it can happen with Bezier strokes, at least in my configuration.


> Here, i remember i drew the periodic table and moved it outside the page, but it still shows up

Since you moved the drawing (and there are no dots), I would suspect this is a different bug. But then, there could also be different contexts that trigger the same bug...
