### ISSUE TITLE
Can't select text at bottom of page

### ISSUE THREAD

**Issue by smellymoo** [adil192/saber#515]
**Describe the bug**
When writting a list of things, there is no way to select the bottom of the list, also moving the page around doesn't seem to work either. 

**To Reproduce**
1. Write multiple lines of text
2. Try to select any at the bottom of the page

**Expected behavior**
Probably that you can scroll the page by dragging with your finger.

**Comment by adil192** [comment]
Please follow the issue template. Which version of Saber are you using?

**Comment by smellymoo** [comment]
Device: samsung xcover pro 2
OS: android 13
Version: 0.9.6

Sorry, forgot for this issue.

**Comment by adil192** [comment]
Ah okay, I'm going to mark this as a duplicate of #213 which was fixed in v0.9.11

**Comment by smellymoo** [comment]
As long as they are duplicates, as it's more that you can't scroll while doing text, meaning the onscreen keyboard blocks access to lower lines of text.

**Comment by adil192** [comment]
Done!
