### ISSUE TITLE
[NEXTCLOUD HELP] I can't login in Nextcloud in Saber

### ISSUE THREAD

**Issue by muhammadbahaa2001** [adil192/saber#523]
### Describe the bug

I can't login in Nextcloud because I don't know where I don't know/set encryption password

### To reproduce

Settings-->Login-->Sign up-->How to get/set encryption password?

### Expected behavior

I was expecting the application password or two factor authentication to be password encryption.

### Saber version

0.10.0.10000

### Device

- Device: [e.g. Huawei Honor 6x]
- OS: [e.g. Android 7]

**Comment by adil192** [comment]
> The encryption password is used to encrypt your data before it is sent to the server. You choose it when you first login to Saber, and is not related to your Nextcloud account/password.\n\nNo-one can access your notes on the server without your encryption password. This also means that if you forget your encryption password, you will lose access to your data.

This was added to the FAQ in #500
