### ISSUE TITLE
[FEAT] DIsplay the changelog in the update dialog

### ISSUE THREAD

**Issue by adil192** [adil192/saber#527]
### Motivation

Users don't know what to expect from the new update.

### Solution

Display the changelog in the update dialog.

### Saber version

v0.11.1 (11010)

### Device

- Device: Google Pixel 6
- OS: Android 13

**Comment by alanbosco003** [comment]
@adil192  could you please assign this issue to me?

**Comment by adil192** [comment]
absolutely!

**Comment by adil192** [comment]
In `UpdateManager.dart` there's already code to find the latest versionCode (e.g. 11010). Also in that file there's code for the update dialog widget.
The changelog can be found at e.g. `metadata/en-US/changelogs/11010.txt` (I think that's the right path)

**Comment by adil192** [comment]
> <img width="426" alt="Screenshot 2023-04-04 at 9 47 26 PM" src="https://user-images.githubusercontent.com/67573902/229854464-bacbfaa8-7966-4233-962d-3301455c3bd1.png">
> This is the update dialog widget you are referring to right?

Nope that's the about dialog.
The update dialog only shows if you're not on the latest version

**Comment by alanbosco003** [comment]
Where is that widget placed? or when do the user see that widget?

**Comment by adil192** [comment]
Also you appear to be using `lib/main_snap.dart` which disables the update mechanism

**Comment by alanbosco003** [comment]
which flavor do I need to use?

**Comment by adil192** [comment]
> which flavor do I need to use?

just use the regular `lib/main.dart`

**Comment by alanbosco003** [comment]
Ok thanks

**Comment by alanbosco003** [comment]
<img width="504" alt="Screenshot 2023-04-05 at 11 50 50 PM" src="https://user-images.githubusercontent.com/67573902/230169799-febbeb6d-98cc-4d93-b555-c6d700447d77.png">
Do I need to replace the "new version of the app available" with the updated features? or show the updated features below it?

**Comment by adil192** [comment]
Preferably show the changelog below it, thanks

**Comment by alanbosco003** [comment]
Do I need to manually download the changelog or you are already downloading it and saving it somewhere? If I need to manually download it can you please post the whole link?
Thanks

**Comment by alanbosco003** [comment]
Hey, can you put the complete API like to download the changeLog file am not able to download the file.

**Comment by adil192** [comment]
https://raw.githubusercontent.com/adil192/saber/main/metadata/en-US/changelogs/11020.txt

**Comment by alanbosco003** [comment]
Thanks @adil192

**Comment by alanbosco003** [comment]
https://github.com/adil192/saber/pull/543 please check
