### ISSUE TITLE
[BUG] libsuper_native_extensions.so no such file

### ISSUE THREAD

**Issue by kimhanm** [adil192/saber#528]
### Describe the bug

Program does not start:
```bash
saber: error while loading shared libraries: libsuper_native_extensions.so: cannot open shared object file: No such file or directory
```

### To reproduce

1. Install as flatpak `flatpak install com.adilhanney.saber` (using flathub repo)
2. launch ( `com.adilhanney.saber`)

### Expected behavior

Program starts.

### Saber version

0.11.0

### Device

- Device: x86-64-pc-linux-gnu
- OS: arch linux
- Flatpak 1.15.4

**Comment by adil192** [comment]
Thanks for the report! The update has now been published to the Flathub repo. Please reopen this if it doesn't solve your problem.
