### ISSUE TITLE
Eraser erases on all pages simultaneously

### ISSUE THREAD

**Issue by rusty-snake** [adil192/saber#53]
https://user-images.githubusercontent.com/41237666/199598431-16b53eaa-a565-46ef-aeb1-7eae2ec0c166.mp4

Pixel 6
GrapheneOS (AOSP 13)
Saber 0.3.13 from IzzyOnDroid

**Comment by adil192** [comment]
Oh wow that's not good!!

**Comment by adil192** [comment]
Thanks for reporting this
