### ISSUE TITLE
[BUG] Snap build fails

### ISSUE THREAD

**Issue by soumyaDghosh** [adil192/saber#530]
### Describe the bug

Saber doesn't builds when it's built for linux. 

### To reproduce

Check this workflow action to get more details.
https://github.com/soumyaDghosh/saber/actions/runs/4608540653/jobs/8144876332

### Expected behavior

It should have built properly

### Saber version

0.11.1

### Device

- Device: Linux
- OS: Ubuntu-latest(22.04)

**Comment by adil192** [comment]
The new builds require Rust to build, it might be that

**Comment by soumyaDghosh** [comment]
Can you please check this action to see what's wrong with the build.
https://github.com/soumyaDghosh/saber/actions/runs/4614586991/jobs/8157673469

**Comment by soumyaDghosh** [comment]
Where is the binary file of the saber actually saved after this build?

**Comment by adil192** [comment]
https://docs.flutter.dev/development/platform-integration/linux/building#preparing-linux-apps-for-distribution

**Comment by soumyaDghosh** [comment]
All the bugs are solved. Thanks for your mention and co-operation.
