### ISSUE TITLE
Release notes translation

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#549]
This issue comes from discussion with @adil192 for commit 96a61199e49f6116c50ed7d8cd81ca33c13a42e4.

Since this commit, Saber shows release notes to all users (includes users with Czech or other language set). They see English release notes but they don't understand them (when don't speak English too much or at all). Manual translating isn't the best idea (as @adil192 noted in referenced discussion) because it slows down updating process. So, what about using automated machine translation for these messages? Nowadays machine translation using language models is pretty good, so for release notes it should be good enough. I have Deepl on mind, e.g.

**Comment by adil192** [comment]
I ended up using Google Translate. If you or other translators see an error in the automatic translation, please submit a PR editing this file (e.g. `metadata/cs/changelogs/11020.txt`)
```dart
'metadata/$localeCode/changelogs/$newestVersion.txt'
```

**Comment by ceskyDJ** [comment]
Good choice! I completely forgot about what my work colleague said some time ago. For short texts Google translate works better than Deepl.

**Comment by ceskyDJ** [comment]
I looked on current translations and saw they are pretty good. I think there is no need to fix anything (at least for now, we'll see how it will be going for future release notes). I'm glad to see it works well.

**Comment by adil192** [comment]
That's good to hear :)
