### ISSUE TITLE
Empty preview of staff background pattern

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#557]
### Describe the bug

Preview of staffs background pattern is empty, so looks like page without pattern at all. When I select it, it works just fine.

### To reproduce

1. Create new note
2. Go to note settings (3 dots icon in the top right corner)
3. In the section "Background pattern" scroll to the end (horizontally)
4. See the last (in my version, after that it will be penultimate, I think) preview of background pattern for staffs is "empty" (there is only while)

### Expected behavior

The preview of staffs background pattern is displayed like for other patterns.

### Saber version

v0.11.2 Google Play (11020)

### Device

- Device: Samsung Galaxy Tab S8
- OS: Android 13
- Browser: Not applicable in any possible case (web support has been dropped out)

### Anything else?

This is just detail but is drives me crazy for some reason. Ah, I know... I'm just a perfectionist, so I'm sorry, @adil192.

By the way, here is a screenshot I forgot to insert for the first time :D:
![tempFileForShare_20230409-204423](https://user-images.githubusercontent.com/48548230/230801428-196e02c7-63ee-4cdf-bc56-38caa1fbddde.jpg)

**Comment by adil192** [comment]
You're in luck, I've just fixed this today in https://github.com/adil192/saber/commit/67060aca257fe03f7be745286ef6956db6ed23f0

**Comment by ceskyDJ** [comment]
So, good job! Thanks for fixing that ❤️!
