### ISSUE TITLE
Translatable descriptions for app stores

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#558]
I think, I've already translated descriptions (short and long) displayed in F-Droid and Google Play for some mobile applications. Have you looked at it yet? The app is still in construction now, so there is no rush for this but it will be good to have these stuff translated, too. It is a few strings only (and it don't change too much after releasing stable version), so I think, it shouldn't be a problem for translators.

**Comment by ceskyDJ** [comment]
I forgot about Flathub but I don't know if it is possible to translate descriptions displayed there.

**Comment by adil192** [comment]
https://github.com/adil192/saber/blob/2ddb11d497e2375b3c6dfa40944b7e644b11c4f9/flatpak/com.adilhanney.saber.metainfo.xml#L29-L32

> In metainfo files, this tag should be translated by-paragraph, meaning that in a translated file, each translated \<p/> child has a language property. 
> https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description

Looks like we need to add a `<p language="cs"> ...  </p>` tag here for Flathub.


***


As for F-Droid and the Play Store, we can just copy
[`metadata/en-US/full_description.txt`](https://github.com/adil192/saber/blob/main/metadata/en-US/full_description.txt)
and
[`metadata/en-US/short_description.txt`](https://github.com/adil192/saber/blob/main/metadata/en-US/short_description.txt)
to
`metadata/cs/`

**Comment by ceskyDJ** [comment]
Ok, I'll take care of the Czech translation today. Maybe add some help to README's section about translations?

**Comment by adil192** [comment]
Do you have anything specifically you'd like to change about the new README section?

**Comment by ceskyDJ** [comment]
Oh, sorry, you have already changed it. I think it's ok in this form.

There is one thing... Why release notes for Flathub isn't automatically translating, too? They are the same texts as in dialog in Saber, aren't they?

**Comment by adil192** [comment]
See #561, it's just because it's a different format that I've not implemented yet

**Comment by ceskyDJ** [comment]
@adil192, for Flathub it doesn't work as we expected (see screenshots).

![image](https://user-images.githubusercontent.com/48548230/232343649-5e6cd4fd-2cae-4364-9be0-ded1f186972e.png)
![image](https://user-images.githubusercontent.com/48548230/232343694-08abd1f9-adc3-40cf-8d54-271831df69bc.png)
