### ISSUE TITLE
AppImage Support

### ISSUE THREAD

**Issue by NA0341** [adil192/saber#57]
**AppImages** are **single-file binaries** that can (virtually) run **on any Linux machine.**

**_Just 📥 download ➕ ⚙️ execute._**

They need some time to get understood - but once setup they're just another entry in your build pipeline that does all the work on it's own - and provides users with a very versatile software format :blush:

🪧 AppImage: https://github.com/AppImage

**Comment by adil192** [comment]
@NA0341 I've added an AppImage to [v0.3.15](https://github.com/adil192/saber/releases/tag/v0.3.15)
