### ISSUE TITLE
Stylus not detected with Surface Pro 3 on Linux

### ISSUE THREAD

**Issue by scurrvy2020** [adil192/saber#580]
### Describe the bug

I am using this with a Surface Pro 3 on Arch Linux. 

This app doesn't seem to detect the stylus.  I need to use "finger writing" to get it to work.   The stylus works fine with other apps, such as Xournal++, Gimp, mypaint, etc. 

### To reproduce

1. Open Saber
2. Try to write with stylus

### Expected behavior

Able to write with stylus instead of treating it like a finger. 

### Saber version

0.11.3 flatpak

### Device

Surface Pro 3

**Comment by adil192** [comment]
You'll need to file this issue with https://github.com/flutter/flutter

**Comment by scurrvy2020** [comment]
https://github.com/flutter/flutter/issues/63209

looks like it has already been filed and affects all desktop implementations of flutter.
