### ISSUE TITLE
File picker on AppImage requires zenity

### ISSUE THREAD

**Issue by Polux49** [adil192/saber#581]
### Describe the bug

Running `./Saber-0.11.4-x86_64.AppImage` in a terminal, the Saber window opens gracefully. I can create a new note with the [+] button, but when I try to import a PDF as background to the note, **nothing happens** and I get the following messages in the terminal (starting from `ERROR` when I try to import the PDF file). 

```
Gtk-Message: 15:06:38.150: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:06:38.152: Failed to load module "canberra-gtk-module"
(saber:154106): Gtk-WARNING **: 15:06:38.693: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name
(saber:154106): Gtk-WARNING **: 15:06:38.693: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
Gtk-Message: 15:06:38.753: Failed to load module "colorreload-gtk-module"
Gtk-Message: 15:06:38.754: Failed to load module "window-decorations-gtk-module"
flutter: dynamic_color: Accent color detected.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/linux/file_picker_linux.dart:119)
<asynchronous suspension>
#2      FilePickerLinux.pickFiles (package:file_picker/src/linux/file_picker_linux.dart:22)
<asynchronous suspension>
#3      EditorState.importPdf (package:saber/pages/editor/editor.dart:796)
<asynchronous suspension>
#4      _EditorBottomSheetState.build.<anonymous closure> (package:saber/components/toolbar/editor_bottom_sheet.dart:242)
<asynchronous suspension>
```
One of these lines suggests installing `zenity` (only `zensu` was installed). Indeed, after installin `zenity`, the bug disappears. 

### To reproduce

1. Download Saber-0.11.4-x86_64.AppImage.
2. chmod a+x Saber-0.11.4-x86_64.AppImage
3. ./Saber-0.11.4-x86_64.AppImage &
4. Create a new note in Saber, import a PDF in it as background. 

### Expected behavior

I would expect the AppImage to use other graphical dialog boxes when available.

### Saber version

Saber-0.11.4-x86_64.AppImage

### Device

- Device: PC
- OS: Manjaro Linux
- Browser (if applicable): Firefox

**Comment by adil192** [comment]
Please can you download the AppImage from here: https://github.com/adil192/saber/actions/runs/4742753369
and check if you still get this Exception?

**Comment by adil192** [comment]
> I would expect the AppImage to use other graphical dialog boxes when available.

If you're referring to falling back to other dependencies when zenity isn't available, you'll need to make a new issue on https://github.com/miguelpruivo/flutter_file_picker, though I doubt they'll prioritise this.

**Comment by Polux49** [comment]
I have tried with v0.12.5, the problem has disappeared: I could insert a PDF file in a note without crash.
Thanks for that.

However, I have encountered other problems: 
- It is very slow (1-4 seconds between the moment when you draw a line and the moment you can see it.
- I didn't succeed to scroll pages in notes.
- In a note, after taping on Three dots > Delete page, nothing happens (the page is not deleted).

**Comment by adil192** [comment]
Thanks for following up. Please can you file those as separate issues (apart from the first one which is #179)

**Comment by Polux49** [comment]
OK, I'll do this.
