### ISSUE TITLE
F-Droid build of v0.11.4 fails

### ISSUE THREAD

**Issue by licaon-kter** [adil192/saber#590]
ref: https://monitor.f-droid.org/builds/log/com.adilhanney.saber/11040#site-footer

No sure which environment variable is used exactly :shrug: 

/LE  fyi https://gitlab.com/fdroid/fdroiddata/-/commit/9685361d4d0281216ecfc33cfb48fe47415c6e91

**Comment by adil192** [comment]
I see that the [F-Droid page](https://f-droid.org/en/packages/com.adilhanney.saber/) for Saber lists v0.11.3 as successfully built.

Nothing's changed on my end: the plugin that requires the NDK `super_clipboard` is at `0.3.0+2` on both versions.
Has something changed in the build environment?

**Comment by licaon-kter** [comment]
Nothing changed, it's not only in the main server, it does not build for me locally either.

**Comment by adil192** [comment]
Are you able to rebuild v0.11.3 successfully?

**Comment by linsui** [comment]
11.6 builds for me. I feel that it's a network issue.

**Comment by adil192** [comment]
If this helps, in https://github.com/actions/runner-images/pull/7053, they have the following NDK environment variables:

> | Name | Value |
> | --- | --- |
> | ANDROID_NDK |	/usr/local/lib/android/sdk/ndk/25.2.9519653
> | ANDROID_NDK_HOME |	/usr/local/lib/android/sdk/ndk/25.2.9519653
> | ANDROID_NDK_LATEST_HOME | 	/usr/local/lib/android/sdk/ndk/25.2.9519653
> | ANDROID_NDK_ROOT | 	/usr/local/lib/android/sdk/ndk/25.2.9519653

and in https://github.com/actions/runner-images/issues/5930, they have instructions for manually downloading a version of the NDK with:

> ```bash
> ANDROID_ROOT=/usr/local/lib/android
> ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
> SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
> echo "y" | $SDKMANAGER "ndk;21.4.7075529"
> ```

**Comment by Iey4iej3** [comment]
The build for `v0.11.5` is also failed: https://monitor.f-droid.org/builds/log/com.adilhanney.saber/11050#site-footer

**Comment by Iey4iej3** [comment]
The builds for v0.11.6 & 0.11.7 failed:

https://monitor.f-droid.org/builds/log/com.adilhanney.saber/11061#site-footer
https://monitor.f-droid.org/builds/log/com.adilhanney.saber/11070#site-footer

**Comment by adil192** [comment]
I've submitted a merge request at [fdroiddata!13036](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13036) that should fix this problem

**Comment by linsui** [comment]
12010 builds and we finally find the problem...

**Comment by adil192** [comment]
> 12010 builds and we finally find the problem...

Was it [saber - try long ndk form](https://gitlab.com/fdroid/fdroiddata/-/commit/a38fa2f79dea8efaa2e06493009e7d3018a0ad57) that fixed it?

**Comment by linsui** [comment]
Yes,
