### ISSUE TITLE
Application doesn't open on MacOS

### ISSUE THREAD

**Issue by yarub123** [adil192/saber#591]
### Describe the bug

Here is the error: 
<img width="258" alt="image" src="https://user-images.githubusercontent.com/84487964/233552082-f95b31ad-10cc-4aee-9e99-f2b39257f8d7.png">

Tried this with the most recent 4 versions as of April 20, 2023

Here is the problem report for Saber from Mac: 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/84487964/233553190-212986c6-7684-4ee8-9fd7-e1748fcde62e.png">

### To reproduce

Unzip with default arhive utility or unarchiver. Still same issue after trying to open the app. 

Yes the Mac default permission to click open does come up immediately after installing it, but then clicking on the app itself leads to error above "Quit unexpectedly."

### Expected behavior

For the app to open. 

### Saber version

0.11.4

### Device

- Device: MacBookPro 13"
- OS: 13.3.1 Ventura

### Anything else?

I tried "sudo xattr -cr and -rd" as well on separate times and still nothing

**Comment by adil192** [comment]
I'm going to close this as "not planned" since the code signing will be resolved on the App Store. Please track the App Store issue for more info
- #464

Thank you for your patience

**Comment by adil192** [comment]
Saber is now on the App Store and working (at least on my MacBook)
