### ISSUE TITLE
Logging in to nextcloud 26 doesn't work

### ISSUE THREAD

**Issue by tomkort** [adil192/saber#592]
### Describe the bug

Trying to log in to Nextcloud instance fails if Nextcloud version 26 is used.

### To reproduce

Try to log in to Nextcloud instance using version 26.

### Expected behavior

I expected to get logged in to Nextcloud or get more descriptive error message.

### Saber version

v0.11.4

### Device

- All devices are affected.

### Anything else?

When the logging in fails the default error message seems to be "Log in failed, please check your details and network connection."

While debuggin we can actually see response from the login api apparently isn't what it expects and fails.
![image](https://user-images.githubusercontent.com/5188685/233631893-f3146d0c-e19d-4a75-8479-5948ff76fb97.png)

### Proposed solution
Upgrade the nextcloud-neon client to use ref [c1fd468521917c2ffcd94833c8949c88e42cc75a ](https://github.com/provokateurin/nextcloud-neon/commit/c1fd468521917c2ffcd94833c8949c88e42cc75a)or later.

**Comment by adil192** [comment]
Following https://github.com/provokateurin/nextcloud-neon/issues/226, we're waiting for when my server can be updated to Nextcloud 26 since both versions can't be supported at the same time
