### ISSUE TITLE
Re-login fails and second device login fails

### ISSUE THREAD

**Issue by akail** [adil192/saber#593]
### Describe the bug

I am unable to login to the same self-hosted account from multiple devices, nor am I able to log back in on the same devices using the same exact credentials.  I am able to log back in after deleting the `Saber` folder. 

### To reproduce

For same device:
1. Delete Saber directory
2. Log in to custom nextcloud server
3. Return to login page
4. Re-enter exact credentials
5. Log now shows as fails.
6. Delete Saber directory
7. Log in now works

For second device:
1. Delete Saber directory
2. Log in to custom nextcloud server
3. Go to second device
4. Enter exact credentials
5. Log shows as fails.

### Expected behavior

1. Be able to logout and log back in on the same device
2. Log in with multiple devices

### Saber version

0.11.3, 0.11.4, 0.11.3 f-droid

### Device

- Device: Samsung Tab S8+
- OS: Android 13

and

- Device: Workstation
- OS: Linux - EndeavourOS (Arch Linux) 23.1

### Anything else?

More details on my nextcloud instance:

* Nextcloud Version 25.0.5
* SSL Certificates provided by Lets encrypt
* Traefik Reverse Proxy
* 2FA enabled, using app password specifically for Saber

I will be checking into the logs later today/this weekend to see if I can provide any more details to make sure Traefik or other settings aren't getting in the way.  If there is a way to generate more detailed logs with Saber I could help narrow this down further.

I'm really excited to have found this app as it checks all the boxes I want for doing handwritten notes synced to Nextcloud. Thank you for creating it.

**Comment by akail** [comment]
Noticed there was an update supporting Nextcloud 26.  Had recently upgrade to 26 and also updated all my clients to 0.12.3.  The issue with empty files appears to have resolved, but login with a second device and re-login on the same device is still failing.

**Comment by Ebypotato** [comment]
Hi, I'm not really conversant with GitHub, I would have left my comments
there 😅. Firstly, I would love to say well done! This is such a wonderful
app and I only discovered it after I stopped using Samsung notes. I was
looking for a good replacement and this is it!

My complaint however is that the windows PC version doesn't recognise pen
input. I normally use a graphics drawing tablet with my laptop but while
using the saber app, I cannot use it to write. It doesn't recognise it. It
only accepts the mouse input. Can something be done about it since it's
much easier to write using a graphics tablet than a mouse?

Keep up the good work
Much appreciated ❤️

**Comment by adil192** [comment]
> Hi, I'm not really conversant with GitHub, I would have left my comments there 😅. Firstly, I would love to say well done! This is such a wonderful app and I only discovered it after I stopped using Samsung notes. I was looking for a good replacement and this is it! My complaint however is that the windows PC version doesn't recognise pen input. I normally use a graphics drawing tablet with my laptop but while using the saber app, I cannot use it to write. It doesn't recognise it. It only accepts the mouse input. Can something be done about it since it's much easier to write using a graphics tablet than a mouse? Keep up the good work Much appreciated ❤️

Hi, this is an upstream issue re Flutter. Also in the future, please file a separate issue.
- See https://github.com/flutter/flutter/issues/65248

**Comment by akail** [comment]
This issue has been resolved apparently so I am going to close it.  Login works for me with multiple devices on v0.12.9.  Not sure where it was fixed but now I can really try this app as a daily driver.
