### ISSUE TITLE
Use both rtl and ltr templates

### ISSUE THREAD

**Issue by xmha97** [adil192/saber#601]
### Motivation

Thanks for adding R2L Template: https://github.com/adil192/saber/issues/576

![Screenshot_2023-04-24-21-32-08-901_com adilhanney saber](https://user-images.githubusercontent.com/23485114/234079750-ba01ae51-6956-4666-81a3-8cc3378f248b.jpg)

But the language of the Saber app is English and I want to write Persian. (R2L language)
Now, every time I want to create a new note, I have to change the language of the app and change it back to English.

### Solution

Add R2L template always when the language of app is English.

### Saber version

0.11.5

### Device

- Device: [e.g. Google Pixel 6]
- OS: [e.g. Android 13]
- Browser (if applicable): [e.g. Firefox]

**Comment by adil192** [comment]
> But the language of the Saber app is English and I want to write Persian. (R2L language)

Would a (global) setting to choose between RTL/LTR templates work for you? Or do you need to use both rtl and ltr templates in different notes?

**Comment by xmha97** [comment]
I need both templates.
Sometimes R2L and sometimes L2R.
I prefer to write my daily tasks in Persian and write programming tips in English.

My suggestion:
If the app was English, the R2L template should be placed at the end, and if the app was Persian, the L2R template should be placed at the end.
You can add an option to display an additional template in the settings.
Thanks.
