### ISSUE TITLE
Add the snap badge

### ISSUE THREAD

**Issue by soumyaDghosh** [adil192/saber#613]
### Motivation

As you said before you didn't like badges but now, as you have added them, can you please add the snap badge also?

### Solution

This is the badge

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-white.svg)](https://snapcraft.io/saber)

### Alternatives

https://snapcraft.io/static/images/badges/en/snap-store-black.svg

### Saber version

0.11.7

### Device

- Device: [ Laptop ]
- OS: [ Ubuntu 23.04 ]

**Comment by soumyaDghosh** [comment]
Also, can you send me a PR to the snap repo. every time there is an update?

**Comment by adil192** [comment]
> Also, can you send me a PR to the snap repo. every time there is an update?

Why don't you just add a GitHub Action or something similar?

**Comment by soumyaDghosh** [comment]
Is that possible that whenever this page has a new tag, it'll change the version to that!!!

**Comment by soumyaDghosh** [comment]
That doesn't seem to be doable from only my repo.

**Comment by soumyaDghosh** [comment]
Yeah, just I'll get a lot of notifications.

**Comment by adil192** [comment]
You can filter it to only notify you when there's a release

**Comment by adil192** [comment]
I'm hesitant to hand out unrestricted read-write access to the repo. We could instead use a system where you submit PRs and I'll just merge them into my repo

**Comment by adil192** [comment]
Also as for the original issue, I'm not ignoring you, I just need to do a little rewrite of the badge section in the README and I've not gotten around to it yet

**Comment by soumyaDghosh** [comment]
Being in a github organisation doesn't give me a complete read-write access, even if I am the collaborator of this repo, I don't get that access.

**Comment by adil192** [comment]
Oh okay so is an organisation a requirement for snapcraft?

**Comment by soumyaDghosh** [comment]
Well, the link will get redirected to the new url, but it's better to change it. And as per the organisation, it's not. I'm suggesting that so that I and you both have the read access to the repo. You'll have complete access tho.

**Comment by adil192** [comment]
> I'm suggesting that so that I and you both have the read access to the repo.

You should already have read access right? Since it's a public repo
