### ISSUE TITLE
Onyx Boox: Stylus stops working if two-finger scroll enabled

### ISSUE THREAD

**Issue by ma-con** [adil192/saber#614]
### Describe the bug

On my Onyx Boox TabUltra, it seems that Stylus (and also finger) input is not saved if scrolling with two fingers is enabled. I’ve tried to record it in the attached video, and I hope one can see that after changing scrolling to two fingers only, nothing happens when trying to write. On the device itself, the pen strokes are sometimes shown but disappear after a screen refresh (which I guess is a thing of the Onyx SDK?).

I haven’t used the app in a while, so I am not sure when this started happening and I also recently updated the tablet to the new onyx version 3.3.2

https://user-images.githubusercontent.com/3628261/235341904-64816469-9022-4dc1-bc71-04bb5a62fb4e.mp4

### To reproduce

1. Start writing, e.g. on the whiteboard with one-finger scrolling enabled
2. Enable two-finger scrolling
3. Try to write

### Expected behavior

Writing should work the same with one- or two-finger scrolling

### Saber version

v.0.11.7

### Device

- Device: Onyx Boox Tab Ultra
- OS: Android 11 (Onyx software version 3.3.2)

### Anything else?

Update: I’ve just realized that the same happens on my iPad Pro (really awesome that saber is now on the AppStore btw.)

**Comment by adil192** [comment]
Thanks for the bug report, this should be fixed in v0.12.0 :)
