### ISSUE TITLE
F-Droid 0.12.3 fails to build

### ISSUE THREAD

**Issue by licaon-kter** [adil192/saber#629]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4241589651#L894

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/abeb402cd8ef1a2a438a800c7599985e81feb993

**Comment by licaon-kter** [comment]
Also in the CI here: https://github.com/adil192/saber/actions/runs/4909651390/jobs/8766179794#step:8:15

**Comment by adil192** [comment]
Yes that's my fault sorry!

**Comment by adil192** [comment]
I've moved the `v0.12.3` tag to the new commit. Will the F-Droid update checker automatically pick this up or should I make a MR?

**Comment by licaon-kter** [comment]
Done https://gitlab.com/fdroid/fdroiddata/-/commit/e5499a279c46acc77e92366442073f89e47a27ad

**Comment by adil192** [comment]
Thanks
