### ISSUE TITLE
Bug while pasting images

### ISSUE THREAD

**Issue by pablo-s-dev** [adil192/saber#633]
### Describe the bug

Images are too small when pasted, and trying to make it bigger does nothing. I found a workarround to it that I thought it would always work: paste it and reopen the doc. But it stopped working on a specific document, the screen freezes after I try to close the doc, forcing me to close the program.

### To reproduce

Paste image using ctrl+v or using the image button

### Expected behavior

I expected that I would be able to resize the image right away and that it would have a bigger size by default

### Saber version

v0.12.3.0

### Device

- Laptop: Thinkpad t430s
- OS: Windows 10

**Comment by adil192** [comment]
I believe this has been fixed with https://github.com/adil192/saber/commit/db20cec1d590d809c8d27a09569f480b44a02a2c. I'm going to close this issue for now but please reopen it if the problem continues after the next update
