### ISSUE TITLE
Zoom/pan lock buttons don't reappear when hovered over

### ISSUE THREAD

**Issue by pablo-s-dev** [adil192/saber#634]
### Describe the bug

The side menu becomes invisible after some seconds, and it doesn't appear back when you hover over it. The buttons only become visible again for some seconds after you scroll down the page

### To reproduce

1. Open a doc
2. Scrol down the page
3. Wait for some seconds until the buttons dissappear
4. Hover over the buttons, they won't become visible 

### Expected behavior

I actually don't expect them to become invisible after some seconds, but at least it should become visible again if you hover on it

### Saber version

v0.12.3.0

### Device

- Laptop: Thinkpad T430s
- OS: Windows 10

**Comment by adil192** [comment]
The buttons are intended not to reappear when hovered over, since then you wouldn't be able to write/draw behind them.
