### ISSUE TITLE
Feature to scroll using the scrollwheel

### ISSUE THREAD

**Issue by pablo-s-dev** [adil192/saber#635]
### Motivation

I dislike having to unzoom to drag outside of the page in order to scroll the page down

### Solution

It's more intuitive to scroll using the scroll and zoom using ctrl + scroll. Please let the user choose 

### Saber version

v0.12.3.0

### Device

- Laptop: Thinkpad T430s
- OS: Windows 10

**Comment by adil192** [comment]
- Duplicate of #178
