### ISSUE TITLE
Can't login to own Nextcloud

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#640]
### Describe the bug

I can't login to my Nextcloud. Password is 100% correct but it gives me a message "Log in failed, please check your detail and network connection.". Saber's Nextcloud works fine.

### To reproduce

1. Install Saber (or log out from currently logged in account when have it already installed).
2. Try to log in to own Nextcloud server (I can provide an access to it if needed, just let me know).
3. It doesn't work and displays error message "Log in failed, please check your detail and network connection."

### Expected behavior

It should log me in just like into official Saber's Nextcloud.

### Saber version

Notebook: v0.12.2 (12020), Phone: v0.12.0 Google Play (12000)

### Device

**Notebook:**
- Device: HP ProBook 450 G5
- OS: Debian 11

**Phone:**
- Device: Samsung Galaxy S22
- OS: Android 13

### Anything else?

![image](https://github.com/adil192/saber/assets/48548230/8ace6325-e5df-4fb1-8510-fbac7ca729a1)

**Comment by ceskyDJ** [comment]
I have two factor authentication enabled, so I use App password for Saber (just for completeness). It works good with other applications.

**Comment by ceskyDJ** [comment]
It looks like log in was successful (at least Nextcloud says something like that in Security section):
![image](https://github.com/adil192/saber/assets/48548230/99f305b3-462a-430a-a1ba-bb9f5fcb80f8)

**Comment by adil192** [comment]
It looks like you have Nextcloud 26.0.1.1 from this [scan.nextcloud.com scan](https://scan.nextcloud.com/results/4a621290-72c0-4efa-ae8a-0bc144e4ba29).
You'll need to use Saber v0.12.3 or later

**Comment by adil192** [comment]
Note that v0.12.4 has just been released which fixes a syncing bug in v0.12.3

**Comment by ceskyDJ** [comment]
Ok, I'll try it when it the new Saber is available.

**Comment by ceskyDJ** [comment]
I tried it. Logging in works in v0.12.3.

**Comment by janaxhell** [comment]
It doesn't work for me: I have tried both F-droid 0.12.4 and Google Play 0.12.5, but it gives the same error mentioned by OP.
I used Saber last year on an old Nextcloud instance that doesn't exist anymore and now on the new one I have no way to use old encryption password OR create a new one. I'm using this on Android 13 and my server is Nextcloud AIO with NC 25.0.6.

**Comment by adil192** [comment]
> It doesn't work for me: I have tried both F-droid 0.12.4 and Google Play 0.12.5, but it gives the same error mentioned by OP. I used Saber last year on an old Nextcloud instance that doesn't exist anymore and now on the new one I have no way to use old encryption password OR create a new one. I'm using this on Android 13 and my server is Nextcloud AIO with NC 25.0.6.

Since [v0.12.3](https://github.com/adil192/saber/releases/tag/v0.12.3) you can only use Nextcloud 26 and not 25. The [nextcloud client](https://github.com/provokateurin/nextcloud-neon/commits/main/packages/nextcloud) Saber uses [only supports the latest version of Nextcloud](https://github.com/provokateurin/nextcloud-neon/issues/226).

**Comment by ceskyDJ** [comment]
@adil192, it isn't my business but number of public Nextcloud hosting companies will use older versions like 25. Maybe it should be at least a little supported. I don't know what plans you have but this isn't the best situation from my point of view, when there is no specific error message. I would hold a complete support for older versions for some time but it's your project, so the decision is all yours. I'm sorry for this note but I can't let it go.

**Comment by adil192** [comment]
I know and I agree that it would be better if I could support both versions. But as I said before, it's out of my hands since it's under the domain of the [nextcloud package](https://github.com/provokateurin/nextcloud-neon/commits/main/packages/nextcloud). You could make an issue on that repo but provokateurin has said they're only supporting the latest version of Nextcloud for the time being.

**Comment by janaxhell** [comment]
Ah ok, then I'll have to wait for Nextcloud AIO to update. But yes, an explicit error message about Nextcloud build would help.

**Comment by ceskyDJ** [comment]
So, @adil192, you don't have any chance to recognize older Nextcloud versions instead of bad login credentials?

**Comment by adil192** [comment]
@ceskyDJ Please see
- https://github.com/adil192/saber/issues/651

**Comment by ceskyDJ** [comment]
Thanks for your effort. I looked at your referenced issue and added some comment.
