### ISSUE TITLE
One unneeded blank page is automatically added at the end of every note

### ISSUE THREAD

**Issue by Polux49** [adil192/saber#644]
### Describe the bug

Whenever I write something on the last blank page of a note, one more blank page is automatically added to the note.  

### To reproduce

1. Open a new note. It consists in one blank page.
2. Write a stroke. A new blank page is added, so the note has now two pages.
3. Write a stroke on page 2. A new blank page is added, so the note has now three pages. 
4. Undo. The third page is deleted. The note consists now in two pages, with a stroke on page 1 and a blank page 2, just as in step 2.
5. Undo again. The second page is deleted. The note consists now in one blank page, jus as in step 1. 

### Expected behavior

Obvious.

### Saber version

v0.12.5 F-Droid

### Device

- Device: OnePlus 6T
- OS: Android 11

### Anything else?

Same behaviour with the AppImage.

**Comment by adil192** [comment]
This is intended behaviour so you can quickly write on a new page without needing to manually add a page

**Comment by Polux49** [comment]
OK. 

Let me point out that this feature _looks_ like a bug with AppImage in the following case:

1. Open a new note in AppImage.
2. Write something, for example "This is a test phrase".
3. It may happen that, at some point of your writing (not necessarily the first stroke), you will be moved to the second page in the middle of your sentence, sometimes even in the third page, so that you finally get "This is" on the first page, "       a test phr" on the second page, and "                 ase" on the third one. 

I understand that this feature of adding automatically one blank page is not directly the problem in itself. Probably it is a combination of it and the laggy issue which causes this buggy-like behaviour.

**Comment by adil192** [comment]
It's not a bother at all don't worry!
But the behaviour you describe definitely shouldn't be happening. Please can you file a new bug report issue? And please include if this happening when handwriting and/or typing
