### ISSUE TITLE
Split per ABIs for Android APKs

### ISSUE THREAD

**Issue by momobobe** [adil192/saber#648]
### Motivation

The APK file now is quite big (> 70 MB, in comparison it was < 30 MB before) as it includes libraries for 4 architectures. To save both bandwidth and storage as well as enhance loading, I feel it worth the work.

### Solution

https://developer.android.com/build/configure-apk-splits

### Alternatives

Or simply ask friendly and experienced F-Droid members, like [licaon-kter](https://github.com/licaon-kter) and [linsui](https://github.com/linsui), for help.

### Saber version

latest

### Device

irrelevant

**Comment by adil192** [comment]
I won't split the APK that's in the GitHub releases, since it makes users guess their architecture. But I've submitted a merge request to split the APKs on F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13101
