### ISSUE TITLE
Build failing again for snap

### ISSUE THREAD

**Issue by soumyaDghosh** [adil192/saber#649]
### Describe the bug

When building the flutter package, I'm getting this

```
FAILED: pdfium-download-prefix/src/pdfium-download-stamp/pdfium-download-test /root/parts/saber/build/build/linux/x64/release/pdfium-download/pdfium-download-prefix/src/pdfium-download-stamp/pdfium-download-test
:: [        ] cd /root/parts/saber/build/build/linux/x64/release/pdfium-build && DOWNLOAD_EXTRACT_TIMESTAMP true && /usr/bin/cmake -E touch /root/parts/saber/build/build/linux/x64/release/pdfium-download/pdfium-download-prefix/src/pdfium-download-stamp/pdfium-download-test
:: [        ] /bin/sh: 1: DOWNLOAD_EXTRACT_TIMESTAMP: not found
```

### To reproduce

Checkout the snap actions
https://github.com/soumyaDghosh/saber/actions/runs/4980383503/jobs/8933805708

### Expected behavior

It should have built properly, this is happening from v0.12.4

### Saber version

from v0.12.4

### Device

- Device: Linux
- OS: Ubuntu 22.04

**Comment by adil192** [comment]
This should be fixed with https://github.com/DavBfr/dart_pdf/issues/1375 (https://github.com/DavBfr/dart_pdf/commit/198a2eae275e404af9167a9c27a9957d22a0184b) but it's not on pub.dev yet.

**Comment by soumyaDghosh** [comment]
Any current patch, how are you building the flatpak anyway?
Same process?

**Comment by florianguyot** [comment]
@adil192, I tested the fix but I am not sure that it fulfills the requirement. 
`cmake_policy(SET CMP0135 NEW)` was introduced in CMAKE 3.24

On Ubuntu 22 (LTS), the CMAKE version on the apt repo is [3.22](https://launchpad.net/ubuntu/jammy/+source/cmake). So the patch requires to manually upgrading the CMAKE of the pipeline in order to compile the code. 

Same problem with this fix on windows : https://github.com/DavBfr/dart_pdf/issues/1375

**Comment by soumyaDghosh** [comment]
Seems like using cmake from snap, which is the latest, is making the job. Pushed the version to `v0.12.6`. 

A suggestion, I'd like to transfer ownership of the snap to you, or atleast add you as a collaborator. Would you like it. I will maintain the snap anyway.

**Comment by adil192** [comment]
Yeah sure you can add me as a collaborator. I probably won't be much help with it though :p

**Comment by soumyaDghosh** [comment]
your email please, which has the snapcraft.io account registered with

**Comment by adil192** [comment]
adilhanney@disroot.org

**Comment by soumyaDghosh** [comment]
Sent, closing this.
