### ISSUE TITLE
Make the Saber settings page look more like the Android Settings app

### ISSUE THREAD

**Issue by adil192** [adil192/saber#655]
### Motivation

Android's Settings app is basically the blueprint for a Material 3 settings page.

### Solution

- Increase the font size of each setting
- Restyle the section headers

<img src="https://github.com/adil192/saber/assets/21128619/dd957ef8-048c-4b4d-829b-d6e708af6481" width="350">
<img src="https://github.com/adil192/saber/assets/21128619/a1c394c3-a88d-40ab-a3ad-b0534648abf1" width="350">

### Saber version

v0.12.6 (12060)

### Device

- Device: Google Pixel 6 Pro
- OS: Android 13

**Comment by rohitsoniinfo** [comment]
Hi @adil192, Please assign Issue #655 to improve Saber settings page to resemble Android Settings app.

**Comment by adil192** [comment]
@rohitsoniinfo Are you still interested in this issue? (There's no rush don't worry)

**Comment by rohitsoniinfo** [comment]
I'm interested but my university exams are going on and I was also busy in
one of my project, as I get my free time I'm gonna work on that.
Thank You for your patience.

**Comment by adil192** [comment]
I'm doing some performance optimisations on the settings page which will overlap with this issue. I'll link them here

**Comment by adil192** [comment]
Updated screenshot:
<img src="https://github.com/adil192/saber/assets/21128619/901b307f-f1e2-476e-90b2-27e2926ff5fd" width="350"> <img src="https://github.com/adil192/saber/assets/21128619/a1c394c3-a88d-40ab-a3ad-b0534648abf1" width="350">

**Comment by adil192** [comment]
Since there was hardly anything left to do, I just changed the text styles and closed the issue.
