### ISSUE TITLE
HELP NOTE just showing blank page - everything lost??

### ISSUE THREAD

**Issue by m0byn** [adil192/saber#656]
Hey everyone, 
I was just editing a note on my Android Tablet. Then, I swiped to the left from the right edge of the screen (return) to go back to all notes. All of a sudden the just edited note shows empty...this note is very important...is there any way to recover it????

I am using Nextcloud sync.

Please help!!

**Comment by m0byn** [comment]
So, I logged into Saber online. There, I figured out which note I am concerned about. Apparently, there exists versioning of the different notes, and I restored the version of the previous ones with the largest file size (34.7 MB) before it shrunk down to 34 KB. The pop-up showed that the version got restored successfully. At the tab showing the different versions the largest one is shown to be the current one. However, the file in the explorer still shows a file size of 34 KB.
I also still cannot see the restored version on my tablet. What do I have to do??

Please HELP! This is actually one of the most important notes...(all notes regarding my master thesis!!)

**Comment by m0byn** [comment]
![Bildschirmfoto 2023-05-20 um 12 15 13](https://github.com/adil192/saber/assets/33026003/36c59177-c0c7-493b-ac42-c3dca60ff15f)
Thank you for helping out. So, the newest version, which I restored online and is showing now as "Current version" has a size of 34.7 MB (screenshot box # 3). When downloading this version the size shows to be 37 KB which is similar to the size of the note showing without versions (screenshot box # 2). The downloaded previous to current version shows a correct file size of 34.6 MB (screenshot box # 4). Is there any way to download the current version with correct size? (screenshot box # 3)

**Comment by adil192** [comment]
If the Last_FULL one isn't downloading correctly, you'll probably have to cut your losses and just go with the Also_OK one

**Comment by m0byn** [comment]
Thank you for your help. It worked! I am very grateful - thank you! Keep up the good work! I believe this app has a great potential!
