### ISSUE TITLE
Prompt user before overwriting an existing note with an empty note

### ISSUE THREAD

**Issue by adil192** [adil192/saber#657]
### Motivation

Following #656, a safeguard against overwriting an existing note with a blank note should be implemented.

### Solution

In the `Editor` class, after a note has been loaded, record whether the note is empty or not.
Then, when saving a note, check if it's empty. If it's empty but it wasn't empty to begin with, we need to ask the user whether they actually meant to completely clear their note. Autosaves should not prompt the user: they should only be asked when manually saving (i.e. exiting a note).

E.g. pseudocode:
```dart
class EditorState {
  EditorCoreInfo coreInfo;
  bool? noteWasEmptyWhenLoaded;

  loadNote() {
    coreInfo = EditorCoreInfo.fromFile(...);
    noteWasEmptyWhenLoaded = coreInfo.isEmpty;
  }

  saveNote(bool causedByAutoSave) {
    if (coreInfo.isEmpty && !noteWasEmptyWhenLoaded) {
      if (causedByAutoSave) {
        print('Cancelled autosave since the note is empty but wasn\'t empty when it was first loaded.');
      } else {
        // trigger a modal with buttons like 'Save anyway' and 'Cancel', and a message like
        // 'This note is empty now but it wasn't empty before the current session. Do you want to save it anyway?'
       triggerConfirmSaveDialog();
      }
      return;
    }

    // otherwise save note as normal
  }
}
```

### Alternatives

It would of course be better to find out why that happened and fix it, but it seems like a hard bug to track down. 

### Saber version

v0.12.6 (12060)

### Device

Unknown as @m0byn didn't specify

**Comment by m0byn** [comment]
Device: Samsung Galaxy Tab S6
Operating System: Android 13 (LineageOS 20)

**Comment by adil192** [comment]
Closing this issue because, since v0.12.10, you aren't allowed to use the Android back gesture until the note has finished saving successfully.
