### ISSUE TITLE
Resize eraser proportionally to zoom

### ISSUE THREAD

**Issue by m0byn** [adil192/saber#664]
I use the zoom feature intensively to fit more content on to one page. In more detail, I zoom to 4x or so, write some content with smallest pen size selected. Then, I zoom out and have a good overview of all the content on one page. The problem happens when I am trying to erase some parts because the eraser covers a predefined and not adjustable area. So, in the case of erasing the area covered by the eraser is just too big and most of the time too much is erased. So, I would recommend to set the eraser size proportionally to the zoom level. I would think of something like eraser area divided by zoom level, or so.

Hopefully this is understandable. If not, I am willing to explain in more detail, or provide screen recordings.

Keep up the good work!!

**Comment by m0byn** [comment]
Duplicate

**Comment by adil192** [comment]
Please use the issue template next time 🙏🏽
