### ISSUE TITLE
Disabling Finger Drawing disables Pen input

### ISSUE THREAD

**Issue by byzocker** [adil192/saber#671]
### Describe the bug

When disabling finger drawing (<img width="32" alt="image" src="https://github.com/adil192/saber/assets/59401089/c49c2d24-aaee-4aa1-9424-e8cd4b694fc0">) pen input only moves the canvas

### To reproduce

1. Disable finger drawing
2. Try to draw with pen

### Expected behavior

The pen drawing

### Saber version

v0.12.8.0

### Device

- Device: Surface Go 2 + Surface Pen
- OS: Windows 11

### Anything else?

#90 related

**Comment by adil192** [comment]
This is an upstream issue from Flutter. Please leave a thumbs-up on this issue:
- https://github.com/flutter/flutter/issues/63209
