### ISSUE TITLE
IPv6 support for Official Nextcloud instance?

### ISSUE THREAD

**Issue by PolarianDev** [adil192/saber#680]
Hello,

So after inspecting the official instance address, I realised it belongs to `AS12488` which is the ASN of `Krystal Hosting Ltd`.

It does not appear they support IPv6, which is pretty bad for a hosting company in 2023, but then again its more of a mainland Europe thing as the UK still control large amounts of IPv4 blocks and do not see the benefit of migrating.

I wouldn't mind but the "free" IPv4 address they give you is factored into the price, a £10 VPS is massively outperformed by the cheapest hetzner servers: https://www.hetzner.com/cloud

More storage space for 5 EUR, 2 cores, 2GB of memory, IPv4 and IPv6 dual stack support.

There might be a reason you picked krystal but I don't see it, and personally I like IPv6 so thats why I am bringing it up.

Lets add some additional issues:
- Your nextcloud instance loads extremely slow, ~5 seconds to load the login page, this could be nextcloud's fault but after doing a file uplaod test, you cant reliably upload to your server (unless again its nextcloud's fault), one second I can upload at ~20mbps anad the next it plummets to ~1mbps, maybe this is some sort of fair use thing at krystal I am not sure.
- Download was fine though, at least that was one plus.

If the networking of the server can't handle 1GB files, then why should anyone pay for 10GB of storage etc etc? that is the point I am trying to make, it wasn't to try to insult the platform.

IPv6 support would be nice 😄 (oh and also European ISPs normally give out IPv6, and only allow IPv4 through NAT64 or a giant CGNAT due to the lower number of blocks, so it is beneficial for non-UK users to be able to have IPv6 support, I am aware within the UK it is not a big deal where every ISP will give out a dynamic IPv4 address without a worry in the world)

Just something to keep in mind :)

**Comment by PolarianDev** [comment]
Seems like upload, and the slow page is nextclouds fault because of poor optimisation, but I am not too sure, been years since I have used nextcloud, I am sure you will know.

**Comment by ceskyDJ** [comment]
It depends on the Nextcloud setup. When you give it just enough RAM, enable caching via Redis, etc., it works well in these tasks. This is a real problem – when the Saber will have many more users (and I believe it will), the performance probably will be even worse. You need to give about 4 GB of RAM just for Saber for the future growth of the user base. Another (something about 1 GB maybe) for caching... Just some points for thinking...

I would look at the current setup and try to tune it up a little. Maybe there will be some hosting company that will support Saber via hosting free VPS or at least a very cheap one. I have had a Storage Box from Hetzner for a few weeks and it looks good. It's really cheap but it works well. You can choose the server location in the EU, so there should not be any problems with legislation after the official public release of Saber (EU has quite strict rules for data processing and it is at least better nor required to have them on servers inside the EU). I don't know if there is an after-brexit exception for this. I hope some lawyer or anyone who has been solving these things will read this and give you better advice than me.

**Comment by PolarianDev** [comment]
> It depends on the Nextcloud setup. When you give it just enough RAM, enable caching via Redis, etc., it works well in these tasks. This is a real problem – when the Saber will have many more users (and I believe it will), the performance probably will be even worse. You need to give about 4 GB of RAM just for Saber for the future growth of the user base. Another (something about 1 GB maybe) for caching... Just some points for thinking...
> 
> I would look at the current setup and try to tune it up a little. Maybe there will be some hosting company that will support Saber via hosting free VPS or at least a very cheap one. I have had a Storage Box from Hetzner for a few weeks and it looks good. It's really cheap but it works well. You can choose the server location in the EU, so there should not be any problems with legislation after the official public release of Saber (EU has quite strict rules for data processing and it is at least better nor required to have them on servers inside the EU). I don't know if there is an after-brexit exception for this. I hope some lawyer or anyone who has been solving these things will read this and give you better advice than me.

The UK data protection act is a modified version of the general data protection act, basically the UK data processing remains compliant with EU.

However a lawyer is always able to give you some more clarity, however if you are able to afford a lawyer then why don't you buy a bigger server xDDDD, lawyers are so expensive.

To be honest, unless you have thousands of users, the likelihood of a lawsuit is very small.

**Comment by PolarianDev** [comment]
_I still care more about IPv6 support than anything else, I like messing with single stack IPv6_

**Comment by ceskyDJ** [comment]
Of course lawyers are very expensive but we (IT guys, girls and other sweet hearts) are pretty expensive, too 😛. I thought about someone who would help with an open-source project for free (I really don't know if there are any lawyers with this mindset...).

**Comment by PolarianDev** [comment]
@ceskyDJ You mad? Lawyers cost about £30-50/hr, and you think you will get one free because its open source?

Lawyers are well known to take money, without any idea of ethics, lawyers represent murderers in court, because its profitable.

Pay the fee, thats what donations are there for. there are some lawyers which will answer your questions in their free time, but if you want GDPR TOS and privacy policies written up, its going to cost you a lot.

**Comment by ceskyDJ** [comment]
I really don't know every lawyer is just as you noted. I don't know anyone but it doesn't seem they don't exist, does it? But maybe you are completely right, lawyers just take care of their business. I'm so glad IT people are so open and kind (at least some of them). This community leads to projects like Linux, Git, our favorite distros, Libre Office, Firefox, ... So, I'm just very optimistic when I see this miracle in the IT industry or just completely mad as you have written 😅.

**Comment by adil192** [comment]
I currently don't have any plans to change hosting company sorry

**Comment by ceskyDJ** [comment]
Ok, it's your choice, of course.

How about the Nextcloud setup, could you look at it, so maybe the performance could be better?
