### ISSUE TITLE
Question: encryption password

### ISSUE THREAD

**Issue by PolarianDev** [adil192/saber#681]
Hello,

I got a question about the encryption password, well a few:

1. I assumed that the encryption password is stored on the client, therefore meaning its good for privacy to prevent the server admin from knowing the contents of the notes. However when you log out, and you attempt to use a different encryption password you get a login error, why?

I am aware the encryption password being wrong would mean you couldn't decrypt the notes, but then who is authenticating that the encryption password is correct?

2. How do you change your encryption password, because you can't simply just change it when logging in as you will get an authentication error.

Thank you,
Polarian

**Comment by ceskyDJ** [comment]
> I am aware the encryption password being wrong would mean you couldn't decrypt the notes, but then who is authenticating that the encryption password is correct?

Saber tries to decrypt data stored on the remote server using the encryption password you have entered. When it is successful, the login succeeds, too. When data can't be decrypted using a given password, it must be wrong.

**Comment by ceskyDJ** [comment]
> However when you log out, and you attempt to use a different encryption password you get a login error, why?

Notes stored encrypted on the server could be accessed only via the right encryption password.

**Comment by ceskyDJ** [comment]
> How do you change your encryption password, because you can't simply just change it when logging in as you will get an authentication error.

I think the answer is already answered in the FAQ in Saber but I give you a similar version:

1. Sync your notes with the server (sync button on the top of the main screen).
2. Log out of Saber app.
3. Go to the Nextcloud server you use and remove a directory called "Saber" from there.
4. Log in back to the Saber app with the new encryption password.

**Comment by PolarianDev** [comment]
Ok, but remote is empty... nevermind you store a configuration file which contains the key, it makes sense now.

Nextcloud must have taken an hour or two to detect the file because it didn't appear at first, so thats why I got confused.

Thanks for the help.

**Comment by PolarianDev** [comment]
Ah I didnt realise you made a post while I was replying xD

**Comment by PolarianDev** [comment]
Anyways thanks for the help, I will close this discussion :)
