### ISSUE TITLE
Problems adding images ⚠️

### ISSUE THREAD

**Issue by GuiSousa135** [adil192/saber#685]
### Describe the bug

Problem 1 - When adding an image to a note with multiple pages, the image does not appear immediately, I often try to exit and re-enter the note or the application to try resolving, but sometimes even this does not solve

Problem 2 - With the image inserted in the note, it is not possible to move it to other pages of the note, disabling to add images on other sheets

### To reproduce

Problem 1 -

1. Add image
2. the image do not appears on app
3. need to go out and go back

Problem 2 -

1. Within image on note
2. Try moving to another page

### Expected behavior

The correct operation would be to add the image in the note as soon as it was selected from the files, then it would appear on the same page where the user is, and can then move and diffuse, without having to close and open the note or the application

### Saber version

v0.12.9

### Device

- Device: Lenovo S145 (i3 8th, 4gb ram, 256gb ssd)
- OS: Linux Mint

- Device: Samsung Galaxy S20 FE
- OS: Android 13

- Device: Samsung Galaxy Tab S6 lite
- OS: Android 12L

The problem was checked in all tested devices

### Anything else?

![Screenshot_20230606-115807](https://github.com/adil192/saber/assets/55188286/9202dead-f2d5-4f43-83f3-699da24cd628)

**Comment by WasteOfO2** [comment]
Moving notes from one page to the other doesn't work as of yet, a bug relevant to this is already open

https://github.com/adil192/saber/issues/405
