### ISSUE TITLE
Can't connect to custom Nextcloud server

### ISSUE THREAD

**Issue by HeyJoFlyer** [adil192/saber#697]
### Describe the bug

I can't get Saber to sync to my custom local Nextcloud server, neither on Linux desktop or the Android app. The server works for other applications.
After hitting "Log in" it immediately says "Log in failed, please check your details and network connection"

Server Settings:
HTTPS (trusted certifacte)
Domain: nextcloud.home (resolved using custom DNS server)

### To reproduce

1. Open Nextcloud Login Page
2. Check "I want to use a custom Nextcloud server"
3. Enter custom Nextcloud Server Domain and credentials
4. Click Log in

### Expected behavior

Being able to log in to nextcloud and syncing notes

### Saber version

0.12.10

### Device

- Desktop (x64)
OS: Linux Mint 21.1
Version: 0.12.10 Flatpak

- Android 13
Version: 0.12.10 F-Droid

### Anything else?

This might be linked to #435

**Comment by adil192** [comment]
Are you able to login to Nextcloud Neon (current latest build at https://github.com/provokateurin/nextcloud-neon/actions/runs/3787903728)?

**Comment by HeyJoFlyer** [comment]
Installed Nextcloud Neon, while trying to connect to the server it says "Unable to reach the server", the same happens while trying to connect to https://nc.saber.adil.hanney.org/. Copying the addresses to a browser works flawlessly.

**Comment by adil192** [comment]
There must be some problem with your network I'm not sure. I've just retested it now and I can login to `nc.saber.adil.hanney.org` successfully with Nextcloud Neon. Regardless, I can't do anything since Saber uses Nextcloud Neon for all Nextcloud functionality, so I'll close this issue
