### ISSUE TITLE
[Android] Ability to scroll pages from the edges

### ISSUE THREAD

**Issue by mecuricat** [adil192/saber#703]
### Motivation

When you zoom out, the pages appear smaller and there is blank space on either edge of the screen which isn't interactive.

### Solution

These edges could be utilized to scroll up or down the pages.

<img src="https://github.com/adil192/saber/assets/89805719/25e6687b-8030-4879-8479-94377809c793" height="300px" />

### Saber version

v0.12.10 F-Droid (12100)

### Device

- Device: Redmi Note 10 Pro
- OS: Android 13

**Comment by adil192** [comment]
It should already work this way; I'm not sure why it isn't for you
