### ISSUE TITLE
Once pictrure is added, can't edit notes

### ISSUE THREAD

**Issue by theIuser** [adil192/saber#713]
### Describe the bug

Once I add picture I can't add any notes.
![grafik](https://github.com/adil192/saber/assets/23708374/4ab00b86-a89d-4d73-a2eb-afbe81784a7a)

### To reproduce

1. create new empty note
2. add picture from local device
3. save note and exit. picture won't show up if you don't do that.
4. open note. find all the tools grayed out.

### Expected behavior

Being able to further edit the notes. Best case even draw on the pictures.

### Saber version

0.12.10 (12100)

### Device

- Device: Acer Notebook with touch support
- OS: Windows 10
- Device: iPhone 7 Plus
- iOS: 15.4.1

**Comment by adil192** [comment]
Thanks for the bug report: you've helped me fix #638!
