### ISSUE TITLE
Support for Nextcloud 27

### ISSUE THREAD

**Issue by AdmerStroh** [adil192/saber#717]
### Describe the bug

Hi,
I recently upgraded my Nextcloud instance to v27.0
When I try to login in saber on a new client, it says:

"The given server is running Nextcloud 27 but this version of Saber only supports Nextcloud 26."

### To reproduce

Try to login with a new client on a Nextcloud 27 instance.

### Expected behavior

It should work.

### Saber version

v0.13.0 (13000)

### Device

Android 13 & AppImage on Linux

**Comment by adil192** [comment]
Saber uses nextcloud-neon for Nextcloud functionality which only supports one Nextcloud version at a time. So we'll need to wait until both
1. Nextcloud Neon adds support for Nextcloud 27
2. I am able to upgrade my server to Nextcloud 27

**Comment by AdmerStroh** [comment]
@adil192 Nextcloud 27 is now supported by nextcloud-neon!

**Comment by adil192** [comment]
Just to manage your expectations, it's probably going to be a while before I can upgrade my server.

**Comment by ceskyDJ** [comment]
@adil192, how it looks like? Nextcloud 27 is already available as a stable release.

**Comment by ceskyDJ** [comment]
@adil192, thanks for moving support up to Nextcloud 27! You can close this issue, btw ;).
