### ISSUE TITLE
Can't move/add images on second page

### ISSUE THREAD

**Issue by theIuser** [adil192/saber#722]
### Describe the bug

Whenever I try to move an image to the second page it won't go beyond the page border. I will just disappear behind it.
If I try to add a new image to the second page it will just show up on the first page. I won't be able to move it to the second page either.

![image](https://github.com/adil192/saber/assets/23708374/e6256e49-404a-4d03-bbae-3530e6a2041c)

### To reproduce

1. add image to first page.
2. try to move it with drag and drop to second page

### Expected behavior

image crosses the boarder to the second page

### Saber version

v0.13.0

### Device

- Device: Acer Notebook with Touchscreen
- OS: Windows 10 Pro

**Comment by WasteOfO2** [comment]
#405
