### ISSUE TITLE
Snap versioning not working

### ISSUE THREAD

**Issue by soumyaDghosh** [adil192/saber#733]
### Describe the bug

So, as said before, after the migration, the versioning of the snap somehow got messed, and it's still showing the version as `0.12.10`. 

### To reproduce

try by installing the snap from any channel

### Expected behavior

It should have shown the proper version

### Saber version

0.12.10 Snap

### Device

- Device: Desktop Linux
- OS: Any

### Anything else?

For now, Users please look over it, the updates are given properly, which you can find within the app itself. We trying to fix it asap.

Keep any eye to this:
https://forum.snapcraft.io/t/versioning-not-working-properly-with-snap-saber/35677

**Comment by soumyaDghosh** [comment]
Wait, let me have some local tests.

**Comment by adil192** [comment]
Please don't pin issues. You only have collaborator permissions to link the Snap to this repo

**Comment by soumyaDghosh** [comment]
Sorry about that.
