### ISSUE TITLE
Autosave timing control

### ISSUE THREAD

**Issue by GuiSousa135** [adil192/saber#750]
### Motivation

The automatic Autosave is a very important function, but it would be interesting to be able to modify the interval between saves, thus avoiding constant crashes during writing.

### Solution

Possibility to modify the Autosave interval in the app's settings, either with predefined options (example: 10 seconds, 1 minute, 10 minutes, others) or even for the user to enter the desired value.

### Saber version

v0.13.1 F-Droid

### Device

- Device: Galaxy S6 Lite
- OS: One UI Android 12

**Comment by Iey4iej3** [comment]
Probably closely related to my observation: https://github.com/adil192/saber/issues/179#issuecomment-1606222496
