### ISSUE TITLE
Add the ability to create text notes

### ISSUE THREAD

**Issue by iamjosuefischer** [adil192/saber#77]
It will be really cool if you could choose between creating a hand drawing note and only a text note, with a title, body, and add some images to it.

**Comment by JoeJoeTV** [comment]
Maybe there could also be a mix of both, so a note where one could draw and write text(maybe in boxes)?

**Comment by Naheel-Azawy** [comment]
This is a deal breaker for me.
I think the best way to implement this is to have two layers. The lower layer for text and the upper for drawing.

I know this is too much to ask for, but if text ever gets implemented, it would also be a great addition to allow for [org-mode](https://pub.dev/packages/org_flutter) and/or [markdown](https://pub.dev/packages/flutter_markdown)
