### ISSUE TITLE
MacOS app? Or possibly even a Nextcloud app.

### ISSUE THREAD

**Issue by relink2013** [adil192/saber#787]
### Motivation

There seems to be an app for every platform except MacOS. While it’s in no way a deal breaker because iPad is the most important platform for me, it would be very convenient to be able to view & edit notes on desktop. 

### Solution

An x86 macOS build of Saber. 

### Alternatives

An app for Nextcloud itself. This would actually be very welcome as it would more or less give Saber a “WebUI”. 

### Saber version

N/A

### Device

- Device:
- OS:

**Comment by adil192** [comment]
Are you not able to install Saber from the Mac App Store?
https://apps.apple.com/gb/app/saber/id1671523739

**Comment by relink2013** [comment]
Wow either I'm blind or thats new lol. I don't know how I managed to miss that.
