### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by tiritibambix** [adil192/saber#789]
### Motivation

Lack of docker support.

### Solution

Docker support.

### Saber version

Docker

### Device

Docker

### Anything else?

Sorry for the rough aspect of this request.

Any plan on supporting docker anytime soon ? Your work looks really promising.

**Comment by adil192** [comment]
Sorry I don't currently plan to support Docker

**Comment by brahimjarallah** [comment]
Please try doing a wonderful selfhosted docker image which valorise your great work. :) 🥇 
and thanks a lot 👍🏻
