### ISSUE TITLE
Create new Note inside a folder

### ISSUE THREAD

**Issue by s3b3n** [adil192/saber#799]
### Describe the bug

When a note is created inside a folder.
The note is saved at the top folder.

E.g.
Folder a
-> Folder b

After creating note 

Folder a
-> Folder b
Note 1

### To reproduce

1. Create a folder
2. add a note

### Expected behavior

The note is saved where you created it.

### Saber version

0.14.6

### Device

- Device: Galaxy Tab S6 Lite
- OS: Android 13

**Comment by Iey4iej3** [comment]
I think that this issue is still there in v0.14.9, when I click the "+" button bottom right in a folder of "all notes". It has the change that the default file name has folder name in the first characters.

**Comment by Iey4iej3** [comment]
More precisely, I find that, now Saber saves notes precisely in the *parent folder*, with initial characters being the name of the current folder!
