### ISSUE TITLE
Fix snap repo in README

### ISSUE THREAD

**Issue by soumyaDghosh** [adil192/saber#804]
### Describe the bug

The README.md is still showing snap as an unofficial package, with the old url from my repo.

### To reproduce

Check the README.md file

### Expected behavior

I guess you can simply say, 

```
Install it from `snap store`.
`sudo snap install saber`
```

### Saber version

0.14.6

### Device

Linux Platform

**Comment by adil192** [comment]
> The README.md is still showing snap as an unofficial package

This is correct, the snap package is unofficial. I'll update the repo soon
