### ISSUE TITLE
layout size Chinese bug

### ISSUE THREAD

**Issue by Jesse205** [adil192/saber#806]
### Describe the bug

![Screenshot_20230715_224712_com github android](https://github.com/adil192/saber/assets/51242302/0770a99f-a3bc-4cfe-b53e-ef176d1f7d40)
![Screenshot_20230715_230535](https://github.com/adil192/saber/assets/51242302/d9a092b6-2970-4249-8021-a1f730b575c5)

### To reproduce

1. Change language to Simple Chinese
2. see "布局类型" item

### Expected behavior

Change "汽车" to "自动".
Change "药片" to "平板"

Changing "电话" to "手机" is most suitable.

### Saber version

FOSS_v0.14

### Device

- Device: HUAWEI Matepad 11
- OS: HarmonyOS 3.0 Android 12

**Comment by ceskyDJ** [comment]
Simplified Chinese is made by @Sdarfeesh. It isn't one of the most supported translations, so it is a little older (and a lot of strings are just machine translated). You can edit translation of these things yourself at https://github.com/adil192/saber/edit/main/lib/i18n/_missing_translations.yaml. You just replace English strings with Chinese ones, click on "Commit changes..." (in the top right corner), and finish required steps. You will probably need to create a fork of Saber, and after that you just create a pull request, and @adil192 will look at it and merge it, so you'll see changes in one of the closest releases.

**Comment by adil192** [comment]
As ceskyDJ said, all translations are by the community. Sdarfeesh hasn't been active recently so a lot of the Simplified Chinese translation is filled in with Google Translate.
I'll commit this on your behalf but if you're willing, please could you also look through the rest of the missing Simplified Chinese translations and make any neccessary edits? The instructions are here: https://github.com/adil192/saber#extending-existing-languages
