### ISSUE TITLE
gtk4/libadwaita port

### ISSUE THREAD

**Issue by Yisus7u7** [adil192/saber#814]
### Motivation

libadwaita and gtk4 are very visually appealing, plus libadwaita can be used from flutter.

### Solution

Maybe with the use of libhandy, libadwaita, gtk4 and Cairo it can be done.

### Alternatives

.

### Saber version

latest

### Device

- Device:
- OS:

### Anything else?

An [example](https://github.com/flxzt/rnote)

**Comment by adil192** [comment]
Sorry but this would be way too big a workload. I'd welcome a PR if it doesn't overcomplicate things, but otherwise I'm going to close this as not currently planned
