### ISSUE TITLE
Text overflow in folder deletion modal window

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#818]
### Describe the bug

There is an UI error in folder deletion modal window, see:
![Screenshot_20230719_230946](https://github.com/adil192/saber/assets/48548230/638075c5-2a8c-4d2b-b982-a13fb1fd914e)

### To reproduce

1. Open Saber
2. Create new folder
3. Open dialog for deleting of the folder
4. See the message next to the checkbox is overflowing the modal window

### Expected behavior

The message next to the checkbox is wrapped to the next line, so it's not overflowing the modal window.

### Saber version

v0.14.8 (14080)

### Device

- Device: Samsung Galaxy S22
- OS: Android 13

**Comment by ceskyDJ** [comment]
Oh, I'm sorry for my too general title. Thanks for the fix ❤️!

**Comment by adil192** [comment]
Don't worry about the titles, I only change them to make them easier for me to sort through!
