### ISSUE TITLE
Missing label for deleting note

### ISSUE THREAD

**Issue by ceskyDJ** [adil192/saber#827]
### Describe the bug

I noticed delete operation for folders has a label (showed e.g., when you hold a finger on the icon on mobile phones), but the same operation for more doesn't. It's a bit incomplete.

### To reproduce

1. Open Saber
2. Create new note
3. Return to main screen
4. Hold finger on note for displaying actions
5. Hold finger on delete button
6. No label is displayed

### Expected behavior

Label "Delete note" is displayed in this case, like for deleting folders "Delete note" label is displayed.

### Saber version

v0.14.9 (14090)

### Device

- Device: Samsung Galaxy S22
- OS: Android 13

### Anything else?

<img src="https://github.com/adil192/saber/assets/48548230/b8f4c607-4536-4ee6-8f63-9b637693e81b" width=300> <img src="https://github.com/adil192/saber/assets/48548230/14a70b53-e91d-4010-93c3-6014575f39aa" width=300>

**Comment by adil192** [comment]
Thanks
