### ISSUE TITLE
The waste of space with editor toolbar top aligned

### ISSUE THREAD

**Issue by Iey4iej3** [adil192/saber#828]
### Describe the bug

There is a waste of space when the editor toolbar is top aligned.

### To reproduce

1. Set "alignment of the editor toolbar" to be top;
2. Scroll down the canvas

### Expected behavior

The vertical space of editor toolbar reduces.

### Saber version

v0.14.7 F-Droid (14070)

### Device

- Device:
- OS: Android 13

### Anything else?

This issue does not happen when the editor toolbar is bottom aligned, so I think that this is a bug.

**Comment by adil192** [comment]
![Screenshot_20230720-155141](https://github.com/adil192/saber/assets/21128619/e8d70a06-df2a-4072-be15-da366d22ecca)
Please can you explain some more about where the wasted space is?
