### ISSUE TITLE
Show file size for notes

### ISSUE THREAD

**Issue by Iey4iej3** [adil192/saber#857]
### Motivation

1. It would help debug issues about file size more easily;
2. It would help users understand the file size and the size efficiency for every tool, so that users can opt for tools when the storage is limited.

### Solution

1. Show file size for each note;
2. Show total filze size for every directory.

### Saber version

v0.14.10 F-Droid (14100)

### Device

- Device:
- OS: Android 13

**Comment by ceskyDJ** [comment]
I think this is not a good idea. General users don't want to handle file sizes (don't need to). Maybe better will be adding an option for exporting some debug information from Saber, where this information will be (except others). It should be somewhere in advanced settings.

**Comment by ceskyDJ** [comment]
We need to solve #647 well, so this won't be a problem. You (as an app user) should not need to check what features you can use to minimize used storage space. I think we can do it better, so any feature will have minimal impact on storage and performance. Some other apps (like Samsung Notes) do it just like that and they are very usable.

**Comment by Iey4iej3** [comment]
> I think this is not a good idea. General users don't want to handle file sizes (don't need to). Maybe better will be adding an option for exporting some debug information from Saber, where this information will be (except others). It should be somewhere in advanced settings.

I would call them "debug settings" (many open source apps have that, to test more low-level manipulations).

**Comment by ceskyDJ** [comment]
Or maybe include file size as opt-in in debug settings could work well.

**Comment by adil192** [comment]
As @ceskyDJ said, I don't think users should concern themselves with file sizes or even the concept of a file in general.
For debugging, desktops can see the file sizes with the system file explorer.
