### ISSUE TITLE
Options to optimize file size of notes

### ISSUE THREAD

**Issue by Iey4iej3** [adil192/saber#858]
### Motivation

1. Allow users to truncate the file size (by choosing unimportant data in notes) when the storage is limited.
2. Users uses some mode which might unexpectly make the file size larger than necessary. It would be better if the user can later suppress these unnecessary data.

### Solution

Several options:

- [ ] Reduce the precision in existing notes as what is done in https://github.com/adil192/saber/pull/851
- [ ] Suppress the pressure data in existing notes.

### Saber version

v0.14.10 F-Droid (14100)

### Device

- Device:
- OS: Android 13

**Comment by ceskyDJ** [comment]
I think it will be better to just solve the root problem – see #647.

**Comment by adil192** [comment]
Closing as with https://github.com/adil192/saber/issues/857#issuecomment-1657250995
