### ISSUE TITLE
Cannot force delete a locked file on your nextcloud server

### ISSUE THREAD

**Issue by Iey4iej3** [adil192/saber#862]
It seems to me that your nextcloud server is not configured so that the users can unlock their own files in order to delete them. Sometimes I want to delete recursively the directory Saber to debug, and it happens from time to time that some files are locked.

**Comment by adil192** [comment]
I've configured the server to use Redis for file locking so hopefully this shouldn't happen anymore?

**Comment by Iey4iej3** [comment]
Seemingly this does not seem to have an effect for an already locked file — I still get an error when I try to delete a particular file (to be more precise, it is a priori unclear whether this file is locked, but after searching online, others say that this error happens when I try to delete a locked file).

**Comment by Iey4iej3** [comment]
It might be better to set up an expire for file locks: https://github.com/nextcloud/files_lock

**Comment by ceskyDJ** [comment]
Redis is a good choice for Nextcloud transactional file locking (see Nextcloud docs – https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html).

I don't know, if the manual management of Saber's files is a wanted behavior. It could cause potential problems in the app after modifications.

Maybe there should be a safe button for cleaning all stored data in the app, but I don't know. It's up to @adil192.

**Comment by adil192** [comment]
@Iey4iej3 I've added the `files_lock` app to my server. Does this allow you to unlock files that weren't locked by `files_lock`?

**Comment by Iey4iej3** [comment]
It seems to work.
