### ISSUE TITLE
AppImage version not starting - error related to missing libjsoncpp.so.25

### ISSUE THREAD

**Issue by jsghjsgh** [adil192/saber#870]
### Describe the bug

I had issues to start the AppImage provided - tried first Saber-0.14.11-x86_64.AppImage but later also Saber-0.14.2-x86_64.AppImage and Saber-0.14.10-x86_64.AppImage. Starting the AppImage (via shell) results in this error message:

`/tmp/.mount_Saber-xyzXYZ/saber: error while loading shared libraries: libjsoncpp.so.25: cannot open shared object file: No such file or directory`

I resolved the issue in the end by installing `libjsoncpp25` from repository. But I am wondering why this is - shouldn't the library be part of the AppImage or do I misunderstand the concept of AppImage vs. Flatpack/Snap?

### To reproduce

1. Download AppImage
2. Make AppImage executable
3. Open shell at file location
4. `./Saber-0.14.11-x86_64.AppImage`

### Expected behavior

Start of Saber without having to install the missing library as it should be part of AppImage (if I am not mistaken).

### Saber version

Saber-0.14.11

### Device

- Device: Intel NUC 8 i5
- OS: Linux Mint 21.2 Cinnamon, Kernel 5.15.0-78

**Comment by ceskyDJ** [comment]
You are right, as https://docs.appimage.org/reference/best-practices.html notes:
> The AppImage needs to include all libraries and other dependencies that are not part of all of the base systems that the AppImage is intended to run on.
