### ISSUE TITLE
Unable to deselect a note after long-press

### ISSUE THREAD

**Issue by awwRoar** [adil192/saber#872]
### Describe the bug

On long-pressing a note in the usual view, I get three buttons (please label them) and to revert back to the usual view - I have no other option than long-pressing on the note again. I expected it to go back to normal view when I tap 
(a) outside of that note in the empty area (does nothing at present) 
(b) on that note, away from the said three buttons (straight-up opens the note at present)
(c) the back button or gesture (closes the app fully at present)

### To reproduce

1. Long press on any note until three buttons are shown
2. Try going back to the usual view

### Expected behavior

When I tap 

> a. outside of that note in the empty area (does nothing at present) 
b. on that note, away from the said three buttons (straight-up opens the note at present) 
c. the back button or gesture (closes the app fully at present)

I expect the note to get deselected & return to normal view

### Saber version

v 0.14.11 Google Play 14110

### Device

- Device: Xiaomi Pad 5
- OS: Android 13

**Comment by adil192** [comment]
Currently you can just long press again to hide the buttons.
But I see your point and I'll change it so that the buttons are hidden when you tap the empty area in the note.

**Comment by adil192** [comment]
>  I get three buttons (please label them)

You can long hold on the buttons to reveal their tooltips
