### ISSUE TITLE
Notes with color corrupting when opening in 0.15.1

### ISSUE THREAD

**Issue by ZebraVogel94349** [adil192/saber#884]
### Describe the bug

Colored strokes don't work in Version 0.15.1. All notes containing colored strokes opened in that Version will get corrupted. I think the reason for that is, that the new BSON file format uses int64 instead of int, which is not compatible with the way colors are stored. `color = Color(json['c'] ?? defaultColor.value);` in stroke_properties.dart raises an exception because of that.

### To reproduce

1. Create a note using colors
2. Close and reopen the note
3. It is corrupted

### Expected behavior

Not corrupting the note

### Saber version

v1.15.1 PlayStore

### Device

- Device: Samsung Galaxy Tab S7 FE
- OS: Android 13

**Comment by ZebraVogel94349** [comment]
I noticed, that color values stored in old JSON files are greater than 2^32, which is probably the reason for them being Int64. But I don't know, how the values got so big.

**Comment by adil192** [comment]
Thanks for the heads up
