### ISSUE TITLE
Possible print statement left in production?

### ISSUE THREAD

**Issue by PolarianDev** [adil192/saber#886]
Hello,

While I was testing the saber package on Arch Linux when I managed to build it, I found the following:

```
❯ saber
OnLoad

(saber:32345): Gdk-CRITICAL **: 23:53:08.788: gdk_window_get_state: assertion 'GDK_IS_WIN
flutter: dynamic_color: Accent color detected.
```

I assume printing `OnLoad` was something used within development?

Just a heads up, nothing important :D 

Polarian

**Comment by adil192** [comment]
I don't think it's coming directly from Saber: it could be one of the dependencies but I'm not sure.

**Comment by adil192** [comment]
```console
ahanney@pop-os:~$ flatpak run com.adilhanney.saber
Gtk-Message: 14:01:37.333: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:01:37.336: Failed to load module "canberra-gtk-module"
flutter: dynamic_color: Accent color detected.
ahanney@pop-os:~$ 
```
There's no "OnLoad" being printed with the Flatpak, so maybe it's to do with your AUR package

**Comment by PolarianDev** [comment]
Hm...

Maybe it is something wrong with the flutter native build 🤔
