### ISSUE TITLE
Option to disable pressure sensitivity

### ISSUE THREAD

**Issue by Sdarfeesh** [adil192/saber#89]
Add an option to toggle stroke

**Comment by adil192** [comment]
Please can you describe a use case for which the existing "finger drawing" toggle doesn't solve your problem?

**Comment by Sdarfeesh** [comment]
> 

Drawing without stroke, like painting instead of writing

**Comment by Sdarfeesh** [comment]
> Please can you describe a use case for which the existing "finger drawing" toggle doesn't solve your problem?


https://user-images.githubusercontent.com/50188628/204515536-8fdfa335-817b-4adf-a5f8-570126d33a59.mp4

Add an option to disable adjusting thickness by drawing speed

**Comment by adil192** [comment]
It's your lucky day! I've just implemented that earlier today in d508bc460ee5cd96bee611e3797c8d3cfe5615d6

**Comment by adil192** [comment]
Closed with [Release v0.4.2](https://github.com/adil192/saber/releases/tag/v0.4.2)
