### ISSUE TITLE
Image is not imported to current page

### ISSUE THREAD

**Issue by Luciogi** [adil192/saber#912]
### Describe the bug

It is really hard to predict where image will show 

### To reproduce

1. Add image

### Expected behavior

image should be imported on currently visible page

### Saber version

0.15.3

### Device

- Device: Redmi 9T
- OS: Android 13

### Anything else?

Weird behaviors
- When doing full zoom into page , then adding image, it adds image on last page
- When creating new notes file, if user add image on first page (without any stokes on page), the next page is not generated

**Comment by Luciogi** [comment]
https://github.com/adil192/saber/assets/84625092/539abe17-1e7a-4829-b120-74700f1f5f23

**Comment by Luciogi** [comment]
[images.webm](https://github.com/adil192/saber/assets/84625092/d44b8476-48bf-47d8-b5d6-8aa25d304973)

**Comment by adil192** [comment]
I think I've fixed these issues now, please reopen the issue if the next version doesn't fix this

**Comment by Luciogi** [comment]
Fixed
