### ISSUE TITLE
Impove PDF imports 

### ISSUE THREAD

**Issue by ColoursofOSINT** [adil192/saber#930]
### Motivation

As far as I understand, PDF are converted to an image then imported. 

Is possible allow for importing from the main page?

One could select a slide deck and the import it form the "create new note function" and the slides would be able annotate.

### Solution

Import PDF from main page.

Allow them to be annotated PDFs.

### Saber version

New Feature

### Device

- Device: Google Pixel tablet
- OS: Android 13

**Comment by adil192** [comment]
You should already be able to do this with the "import note" button
<img src="https://github.com/adil192/saber/assets/21128619/e4200c98-1a04-4aab-91a6-0a47f4ba97c8" alt="flyout menu listing the import note button, and the new note button">

**Comment by ColoursofOSINT** [comment]
Sorry about that, it was crashing before when I tried to use a PDF with that function so I assumed it was only for Saber files.
