### ISSUE TITLE
Marker opacity

### ISSUE THREAD

**Issue by comcloudway** [adil192/saber#95]
Would it be possible to have the marker draw the lines with 80% opacity?
Currently, drawing a yellow line and a blue line results in only the blue being visible at a given point.
![Current saber implementation](https://user-images.githubusercontent.com/46848143/204585646-f8fe48d9-f25d-444c-9de1-006fe652dc45.png)

I think it might make more sense to have them overly above one another
![quick krita sketch](https://user-images.githubusercontent.com/46848143/204586183-85c084e1-c61e-47fc-820d-ae72de6392a6.png)
As you can see, the yellow line can still be seen through the blue one.

I'm actually not sure, if this might be solved by #42 (if one would be able to set the alpha value for a given color)

**Comment by adil192** [comment]
This was done deliberately as it looks a lot cleaner when it doesn't overlap. Imagine highlighting a multi-line maths formula and you get that ugly overlap streak in the middle!
Is being able to see the overlap an important feature for you? or just an aesthetic choice?

**Comment by comcloudway** [comment]
I think I do understand why you have them set to be solid colours.
I mean, this does look like a hightmap.
![bad overlap example](https://user-images.githubusercontent.com/46848143/204589602-a649539d-6302-475b-9260-fd82daeb3100.png)
Which is why I would not force this, but have it as an optional feature:

But looking at how real-life markers work, the behaviour seemed somewhat off.

So no, it is not an important feature, (I have yet to check the code) but in case you are already using RGBA colours,
I think that adding the ability to change the alpha (in case one will be able to pick custom colours at some point) should not be that bad.

Right now it just seems like it is a solid colour (but I like the layer approach)

**Comment by comcloudway** [comment]
If I'm not mistaken you use the Flutter `Color` class for the colours, which does appear to have a `withAlpha` and `withOpacity` method, so it should be able to make this an optional feature in the future.

**Comment by adil192** [comment]
Implementation-wise it's a little bit more complicated than that before of the layer system, but it's more of a matter of preference than difficulty. I may revisit this in the future to see if I can get both
- the same color highlighter strokes not to overlap
- different-colored highlighter strokes to overlap

**Comment by comcloudway** [comment]
I have to get back into flutter (if I manage to get it running without glibc),
but couldn't you sort the strokes by colour and then use `saveLayer` to separate the colours into separate layers and set the paint blend mode to `opacity`?

Or would that also overlay the same colours?

But I honestly really like the idea of having different colours overlap, whilst the same colour extends the current highlighted area, because that makes highlighting larger areas so much more easy

**Comment by adil192** [comment]
> I have to get back into flutter (if I manage to get it running without glibc)

Are you perhaps talking about this issue https://github.com/flutter/flutter/issues/115909? The fix for that is to do `sudo apt install lib32stdc++-12-dev`

> but couldn't you sort the strokes by colour and then use `saveLayer` to separate the colours into separate layers and set the paint blend mode to `opacity`?

That's what I was thinking too. I'm just finishing off some other features right now so I'll get to it later

**Comment by comcloudway** [comment]
I'm on Alpine Linux, which uses `muslc` instead of `glibc` and `apk` as a package manager,
so I'm kind of talking about flutter/flutter#73260.

I think I found a solution to the problem, but I have to actually test if it's working, at least I'm able to install flutter now without it throwing any errors.
